.TH AUR-DEPS-SRC 1 2018-02-01 AURUTILS
.SH NAME
aur\-deps\-src \- order dependencies using .SRCINFO files

.SH SYNOPSIS
.SY "aur deps\-src"
.RI [ pkgbase ...]
.YS

.SH DESCRIPTION
\fBaur\-deps\-src\fR takes the names of packages and orders the dependency chains
using tsort.

It is assumed that source directories are already available, and that
\fBaur\-deps\-src\fR is used in the same directory as those source directories.

.SH SEE ALSO
.BR aur (1),
.BR find (1),
.BR tsort (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
