.TH AUR\-BUILD 1 2018-04-12 AURUTILS
.SH NAME
aur\-build \- build packages to a local repository

.SH SYNOPSIS
.SY "aur build"
.BI "\-d " database
.OP \-cfNRsv
.OP \-a queue
.OP \-r root
.OP \--
.RI [ "makepkg args" ]
.YS

.SH DESCRIPTION
Build packages, adding the results to a local repository (usually
configured with a \fIfile://\fR prefix\fR in \fIpacman.conf\fR).

It is assumed that build directories are located in the current
directory, and described in a text file which is taken as argument.

.SH OPTIONS
All arguments after \-\- are passed to \fBmakepkg\fR(8), or
\fBaur\-chroot\fR(1) when \fB\-c\fR is specified.

.TP
.BI "\-a " queue
A text file with directories containing a PKGBUILD. If none is
specified, the current directory is assumed.

.TP
.B \-c
Build packages with \fBaur\-chroot\fR(1).

.TP
.BI "\-d " database
The name of the pacman database.

.TP
.B \-f
Continue the build process if a package with the same name is found
(ignoring the extension). Existing packages will be moved with a
\fI~\fR suffix.

.TP
.B \-N
Do not sync the local repository after building.

.TP
.BI "\-r " root
The root for the repository. The \fIroot\fR is the location for the
pacman database (\fIfoo.db\fR), built packages, and secondary files
such as the files database (\fIfoo.files\fR). This defaults to the
\fIServer\fR value of the configured repository.

.SY Note:
The \fIServer\fR value configured in \fBpacman.conf\fR is used for
\fBpacman\fR sync operations regardless of this setting. See also
\fB\-N\fR.

.TP
.B \-R
Remove old package files from disk when updating their entry in the
database (\fBrepo\-add \-R\fR).

.TP
.B \-s
Sign built packages and the database (\fBrepo\-add \-s\fR) with
\fBgpg\fR(1).  To use another key than the default, the \fBGPGKEY\fR
environment variable can be set to the appopriate key identifier.

.TP
.B \-v
Verify the PGP signature of the database before
updating. (\fBrepo\-add \-v\fR).

.SH ENVIRONMENT

.B AUR_REPO
.RS
The repository used for building packages.
If \fBAUR_DBROOT\fR is not specified, then the entry must be a valid
\fBfile://\fR repository configured in \fBpacman.conf\fR(5).
.RE

.B AUR_DBROOT
.RS
The absolute path to the database corresponding to \fBAUR_REPO\fR.
.RE

.SH NOTES
.SS Repository updates
When building locally (outside a container), \fBpacman \-Syu\fR is run
while restricted to a local repository. This is comparable to
\fBmakepkg \-i\fR, but without subsequent package installation (if a
package was installed before, it is updated to the latest available
version). An interesting side-effect is that pacman considers packages
inside the official repositories "local", and warns if they are newer
than any custom counterpart. Packages which define a \fIreplaces\fR
field are ignored if the target package is installed on the local
system.

Databases are built with \fBLANG=C\fR to avoid libalpm from skipping
entries if the locale is not set (FS#49342). Packages are signed
manually with \fBgpg \-\-batch \-\-detach\-sign \-\-no\-armor\fR
(FS#49946).

.SS Avoiding password prompts
\fBmakepkg\fR(8) must be run as a regular user as of version 4.2, with
privileged operations done via \fBsudo\fR(8). As such,
\fBaur\-build\fR(1) can not be run directly as root. To avoid password
prompts, \fBsudoers\fR(5) can be used instead.

For example:
.EX

  %build ALL = (root) NOPASSWD: SETENV: /usr/bin/makechrootpkg
  %build ALL = (root) NOPASSWD: /usr/bin/mkarchroot, /usr/bin/arch-nspawn

.EE

.SY Note:
If the rule should only apply to certain hosts, replace \fBALL\fR with 
the respective \fIhostname\fR.

.SS PKGBUILD signatures
GPG signatures defined in the \fBvalidpgpkeys\fR array may be
automatically retrieved by setting \fIkeyserver-options
auto-key-retrieve\fR in \fBgpg.conf\fR. See \fBgpg\fR(1) for details.

.SH SEE ALSO
.BR aur (1),
.BR aur\-chroot (1),
.BR pacconf (1),
.BR pacman (1),
.BR makepkg.conf (5),
.BR pacman.conf (5),
.BR makepkg (8),
.BR repo-add (8),
.BR setarch (8)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
