.TH AUR-REPO-FILTER 1 2019-01-24 AURUTILS
.SH NAME
aur\-repo\-filter \- filter packages in the Arch Linux repositories

.SH SYNOPSIS
.SY "aur repo-filter"
.OP \-a
.OP \-d database
.YS

.SH DESCRIPTION
.B aur\-repo\-filter
checks if
.IR package[<cmp><version>]
(taken from standard input) is satisfied by a package in the official
Arch Linux repositories \- that is,
.BR core ,
.BR extra ,
.BR testing ,
.BR community ,
.BR community\-testing ,
.BR multilib ,
or
.BR multilib\-testing .

If found, the package is printed to standard output.  If the package
is provided by a package of a different name, the latter is printed to
standard error.

.SH OPTIONS
.TP
.BR \-a ", " \-\-all ", " \-\-sync
Query all available pacman repositories.
.RB ( "pacsift " \-\-sync )

.TP
.BI \-d " NAME" "\fR,\fP \-\-database=" NAME "\fR,\fP \-\-repo=" NAME
Query a given pacman repository.  Multiple repositories may be
specified by repeating this argument.

.SH NOTES
Due to
.BR expac (1)
limitations,
.BR aur\-repo\-filter (1)
only works with the local pacman configuration in
.BR /etc/pacman.conf .

.SH SEE ALSO
.BR aur (1),
.BR expac (1),
.BR pacsift (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
