.TH AUR-QUERY 1 2021-11-27 AURUTILS
.SH NAME
aur\-query \- send requests to the aurweb RPC interface
.
.SH SYNOPSIS
.SY "aur query"
.OP \-t type
.OP \-b by
.IR pkgname " [" pkgname... ]
.YS
.
.SH DESCRIPTION
.B aur\-query
retrieves package information from an AUR endpoint by sending HTTP GET
or POST requests to the
.UR https://\:aur.archlinux.org/\:rpc.php
RPC interface
.UE
with
.BR curl(1).
.PP
Arguments are taken from the command-line. If the first argument is
.B \-
or
.BR /dev/stdin ,
they are taken from standard input.
.
.SH OPTIONS
The request type and arguments must be compatible to the chosen RPC version (see the
.B AUR_QUERY_RPC
environment variable). The options below assume
.BR "RPC v5" .
.
.TP
.BR \-b ", " \-\-by=\fR<KIND>
Arguments for package search
.RB ( \-\-type=search ).
Can be one of
.BR name ,
.BR name\-desc ,
.BR maintainer ,
.BR depends ,
.BR makedepends ,
.BR optdepends ,
or
.BR checkdepends .
.
.TP
.BR \-t ", " \-\-type=\fR<NAME>
Type of request. Can be one of
.B search
or
.BR info .
.B \

.SH ENVIRONMENT
.TP
.B AUR_LOCATION
The URI of the AUR endpoint. Defaults to
.IR https://\:aur.archlinux.org .
.
.TP
.B AUR_QUERY_PARALLEL
If set to a positive value, transfers are done with
.BR "curl \-\-parallel" .
This requires
.BR curl (1)
version >=7.77.0.
.
.TP
.B AUR_QUERY_PARALLEL_MAX
The amount of maximal parallel transfers (defaults to 15). Translates to
.BR "curl \-\-parallel\-max" .
.
.TP
.B AUR_QUERY_RPC
The URI of the RPC interface. Defaults to
.IR "$AUR_LOCATION/rpc/?v=5" .
.
.TP
.B AUR_QUERY_RPC_POST
If set to a positive value, use HTTP POST for info-type requests.
Defaults to
.IR 1 .
HTTP GET results in a significantly higher number of requests
(potentially leading to rate limiting), so HTTP POST should be preferred
in most cases. Due to FastAPI limitations, the maximum number of
packages queried with HTTP POST is around 27k.
.
.TP
.B AUR_QUERY_RPC_SPLITNO
This variable sets the amount of packages listed per URI when using HTTP
GET for info-type requests. This is used to avoid HTTP 414 errors with
larger sets (>200) of packages
.RI ( FS#49089 ).
Defaults to
.IR 150 .
.
.TP
.B AUR_QUERY_RPC_VERSION
The version for the RPC endpoint. Defaults to
.IR 5 .
.
.SH NOTES
The default set of options for
.BR curl (1)
are
.BR "\-A aurutils \-fgLsSq \-\-tcp\-fastopen" .
.
.SH SEE ALSO
.ad l
.nh
.BR aur\-depends (1),
.BR aur\-search (1),
.BR aur\-vercmp (1),
.BR curl (1),
.BR jq (1)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
.
.\" vim: set textwidth=72:
