.TH AUR-SEARCH 1 2018-03-19 AURUTILS
.SH NAME
aur\-search \- search for AUR package

.SH SYNOPSIS
.SY "aur search"
.OP \-imnv
.OP \-k key
.IR package ...
.YS

.SH DESCRIPTION
\fBaur\-search\fR searches the AUR by multiple strings of packages. The
union of all results is returned. By default, searches are performed
by name and description using the \fIsearchby\fR interface, and
displayed in a brief format.

.SH OPTIONS

.B \-q
.RS
Only display package name, version and description.
.RE

.B \-v
.RS
Display more package information.
.RE

.B \-i
.RS
Use the \fIinfo\fR interface instead of \fIsearchby\fR.
.RE

.B \-d
.RS
Search by package name and description.
.RE

.B \-m
.RS
Search by maintainer.
.RE

.B \-n
.RS
Search by package name.
.RE

.BI "\-k " key
.RS
Sort results via a key, defaulting to \fIName\fR.

Possible choices are \fIName\fR, \fIVersion\fR, \fINumVotes\fR,
\fIDescription\fR (for brief output) or \fIName\fR, \fIPackageBase\fR,
\fIVersion\fR, \fIDescription\fR, \fIURL\fR, \fINumVotes\fR,
\fIPopularity\fR, \fIOutOfDate\fR, \fIMaintainer\fR,
\fIFirstSubmitted\fR, \fILastModified\fR (for \fB-v\fR verbose output).
.RE

.SH SEE ALSO
.BR aur (1),
.BR aur\-rpc (1),
.BR jq (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
