.TH AUR-SRCVER 1 2018-02-01 AURUTILS
.SH NAME
aur\-srcver \- list version of VCS packages

.SH SYNOPSIS
.SY "aur srcver"
.OP \-\-noprepare
.IR pkgbase ...
.YS

.SH DESCRIPTION
.B aur\-srcver
takes the names of packages and lists the current
.I pkgver
of VCS packages. This is achieved by running
.B "makepkg \-\-skipinteg \-od"
and parsing the output.

It is assumed that source directories are already available, and that
.B aur\-srcver
is used in the same directory as those source directories.

.SH OPTIONS
.TP
.B \-\-noprepare
Do not run the prepare() function in the PKGBUILD.

.SH SEE ALSO
.BR makepkg (1),
.BR aur (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
