.TH AUR-FETCH 1 2018-02-14 AURUTILS
.SH NAME
aur\-fetch \- fetch packages from a location

.SH SYNOPSIS
.SY "aur fetch"
.OP \-L log_dir
.OP \-t
.OP \-g
.OP \-r
.YS

.SH DESCRIPTION
.B aur\-fetch
accepts URIs to packages from
.IR stdin ,
and attempts to download them. It is capable of handling
.BR tar (1)
archives and
.BR git (1)
repositories.

.SH OPTIONS
.TP
.BI "\-L " log_dir
The location of where to store the diffs of previously unpacked
archives.

.TP
.B \-t
Downloads the package as a
.I tar
archive with
.BR aur\-fetch\-snapshot .

.TP
.B \-g
Downloads the package as a
.I git
repository with
.BR aur\-fetch\-git .

.TP
.B \-r
Download both packages and their dependencies with
.BR aur-depends (1).

.SH SEE ALSO
.BR aur (1),
.BR aur\-depends (1),
.BR git (1),
.BR tar (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
