.TH AUR-RPC-DEPS 1 2018-02-01 AURUTILS
.SH NAME
aur-rpc-deps \- solve and order dependencies using the aur rpc

.SH SYNOPSIS
.SY aur
.B rpc-deps
.OP \-at
.OP pkgname...
.YS

.SH DESCRIPTION
\fIaur-rpc-deps\fR takes package names and then solves and orders the
dependencies for those packages using the AUR RPC interface.

.SH OPTIONS
.B \-a
.RS
Print the full dependency tree, instead of only AUR packages.
.RE

.B \-t
.RS
Copy retrieved JSON files to a specified directory.
.RE

.SH NOTES
Version information is ignored for dependencies. See \fIFS#54096\fR.

.SH SEE ALSO
.BR aur (1),
.BR aur-query (1),
.BR jq (1),
.BR tsort (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
