.TH AUR-ARROW 1 2018-04-21 AURUTILS
.SH NAME
aur\-arrow \- print package/dependency pairs

.SH SYNOPSIS
.SY "aur arrow" .SRCINFO [.SRCINFO...]
.YS

.SH DESCRIPTION
\fBaur-arrow\fR takes package information from \fB.SRCINFO\fR files
and prints them as \fIpackage<TAB>dependency\fR pairs. Any
dependencies are converted from \fBpkgname\fR to \fBpkgbase\fR or
skipped if absent from the input.

.SH EXAMPLES
The paired output is suitable as input for \fBtsort(1)\fR, provided no
cycles are present. For example:
.EX
  cd ~/.cache/aurutils/sync
  aur arrow */.SRCINFO | tsort
.EE

\fB.SRCINFO\fR can be concatenated before processing to improve
performance:
.EX
  cat */.SRCINFO | aur arrow | tsort
.EE

.SH NOTES
Version information is ignored for dependencies.

.SH SEE ALSO
.BR aur (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
