.TH AUR-QUERY 1 2020-10-25 AURUTILS
.SH NAME
aur\-query \- send GET requests to the aurweb RPC interface
.
.SH SYNOPSIS
.SY "aur query"
.OP \-t type
.OP \-b by
.YS
.
.SH DESCRIPTION
.
.SH OPTIONS
.TP
.BR \-b ", " \-\-by
.
.TP
.BR \-t ", " \-\-type
.
.SH ENVIRONMENT
.TP
.B AUR_DEBUG
.
.TP
.B AUR_QUERY_PARALLEL
.
.TP
.B AUR_QUERY_PARALLEL_MAX
.
.TP
.B AUR_QUERY_RPC
.
.TP
.B AUR_QUERY_RPC_SPLITNO
.
.SH NOTES
As the AUR RPC is limited to GET requests, queries are split by 150
arguments to avoid HTTP 414 errors
.RI ( FS#49089 ).
.
.SH SEE ALSO
.ad l
.nh
.BR curl (1),
.BR jq (1)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
.
.\" vim: set textwidth=72:
