.TH AUR-SYNC 1 2018-02-01 AURUTILS
.SH Name
aur-sync \- download and build aur packages automatically

.SH SYNOPSIS
.SY aur
.B sync
.OP \-AcDfLnprstu
.OP \--ignore
.OP \--no-ver
.OP \--no-view
.OP \--repo
.OP \--root
.OP \--
.I pkgname...
.YS

.SH DESCRIPTION
\fIaur-sync\fR downloads and builds packages automatically to a local
repository. Package names serve as arguments.

If \fIvifm\fR is installed, the downloaded files are shown using vifm
and can be edited. If not, the files are shown in \fIless\fR, or
\fI$PAGER\fR if configured.

.SH OPTIONS
.B \-c, --chroot
.RS
Build packages with makechrootpkg. (\fIaur-build -c\fR)
.RE

.B \-D, --directory
.RS
Set the container path. (\fIaur-build -D\fR)
.RE

.B \-f, --force
.RS
Continue the build process if a package with the same name already
exists. (\fIaur-build -f\fR)
.RE

.B \--ignore
.RS
Ignore a package upgrade. Multiple packages can be specified by
separating them with a comma, or by repeating the \fI--ignore\fR option.
.RE

.B \-p, --print
.RS
Print target packages and their paths instead of building them.
.RE

.B \-s, --sign
.RS
Sign built packages and the database with gpg. (\fIaur-build -s\fR)
.RE

.B \-t, --tar
.RS
Download AUR snapshots (\fI.tar.gz\fR) instead of cloning git
directories.
.RE

.B \-u, --upgrades
.RS
Update all AUR packages in a local repository that are out-of-date.
.RE

.B \--no-ver
.RS
Disable version checking for packages in the queue.
.RE

.B \--no-view
.RS
Do not view downloaded files before building.
.RE

.B \--repo
.RS
Use the specified repository instead of an interactive selection.
.RE

.B \--root
.RS
The location of the repository root. Defaults to the \fIServer\fR
value of the configured repository.
.RE

.B \--continue
.RS
Skip downloading package files.
.RE

.SS makepkg
The default set of options is \fImakepkg -cs\fR.

.B \-A, --ignore-arch
.RS
Ignore a missing or incomplete \fIarch\fR field in the build script.
.RE

.B \-L, --log
.RS
Enable logging to a text file in the build directory.
.RE

.B \-n, --no-confirm
.RS
Do not wait for user input. (\fImakepkg --noconfirm\fR)
.RE

.B \-r, --rmdeps
.RS
Remove dependencies installed by makepkg. (\fImakepkg -r\fR)
.RE

.SH ENVIRONMENT
.B AURDEST
.RS
Determines where build files will be cloned (default:
\fI$XDG_CACHE_HOME/aur-sync\fR). This must be an absolute path.
.RE

.B TMPDIR
.RS
Parent directory for temporary files.
.RE

.SH NOTES
When version checks are enabled (\fI--no-ver\fR is not specified),
build files are only retrieved if the remote (RPC) version is newer
than a version in the pacman database. Checks assume there are no
mismatches between \fI.SRCINFO\fR and \fIPKGBUILD\fR files.

Architecture-specific depends (as introduced with pacman 4.2) are
merged with regular depends in RPC queries. \fBaur-sync\fR workarounds
this by stripping the \fIlib32- \fRsuffix from packages and removing
\fIgcc-multilib \fRif the i686 architecture is detected.

\fItar\fR snapshots are extracted to the \fI$AURDEST/snapshot\fR
directory, in order to avoid conflicts with git.

.SH SEE ALSO
.BR aur (1),
.BR aur-build (1),
.BR aur-fetch (1),
.BR aur-rpc-deps (1),
.BR aur-search (1),
.BR aur-updates (1),
.BR git (1),
.BR jq (1),
.BR less (1),
.BR pacconf (1),
.BR parallel (1),
.BR vifm (1),
.BR pacman.conf (5)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
