.TH AUR-FETCH 1 2018-03-17 AURUTILS
.SH NAME
aur\-fetch \- download packages from the AUR
.
.SH SYNOPSIS
.SY "aur fetch"
.OP \-L log_dir
.OP \-r
.OP \-R
.OP \-v
.IR package " [" package... ]
.YS
.SY "aur fetch"
.OP \-\-confirm\-seen
.IR package " [" package... ]
.YS
.
.SH DESCRIPTION
.B aur\-fetch
downloads packages, specified on the command-line, from the AUR.
.
.SH OPTIONS
.TP
.BI \-L " DIRECTORY" "\fR,\fP \-\-write\-log=" DIRECTORY
The location of where to store the diffs of previously unpacked
archives.
.
.TP
.BR \-r ", " \-\-recurse
Download packages and their dependencies with
.BR aur\-depends (1).
.
.TP
.BR \-v ", " \-\-verbose
Print logs to
.BR stdout .
.
.TP
.BR \-\-format= [ diff | log ]
Specifies the format logs are generated.
.
.TP
.B \-\-reset
Reset to the upstream commit, discarding local changes.
.IP
When neither
.BR \-\-rebase " or " \-\-reset
are specified, the default behaviour is
.BR \-\-reset ,
unless
.BR aurutils.rebase " is set to " true
in which case
.B \-\-rebase
will be used.
.IP
If specified,
.BR \-\-reset " takes precedence over " aurutils.rebase .
.
.TP
.BR \-R ", " \-\-rebase
Instead of resetting to the upstream commit, update with
.BR "git pull \-\-rebase" .
This can be used to keep locally committed changes to PKGBUILDS.
Uncommitted changes are discarded. See
.BR NOTES .
.IP
This feature can be enabled on a per-repository basis by setting
.BR aurutils.rebase " to " true
in the git configuration.
.
.TP
.B \-\-confirm\-seen
Marks the package's checked out commit as seen. See
.BR NOTES .
.
.TP
.BI \-\-results= file
Writes
.IB action :file:// path
pairs to the specified
.IR file .
Possible values for
.I action
are
.B clone
and
.BR fetch .
.I path
is the absolute path to the processed package repository.
.IP
Can be used by higher level tools to differentiate new clones from
updates to existing repositories.
.
.
.SH NOTES
.
.SS LOGS
The logs shown by
.BR aur\-fetch (1)
show changes that happened since the commit referenced by the
special reference
.B AUR_SEEN
stored inside the repository.
.PP
This reference can be created with with:
.PP
.EX
    \fB$ aur fetch \-\-confirm\-seen \fI<package> \fR[\fP<package>...\fR]\fR
.EE
.PP
which will mark the current commit as seen, signaling
.BR aur\-fetch (1)
that current changes should not be shown in future logs.
.
.
.SS REBASE
This option should be used with care. While it enables users
to keep personalized changes to PKGBUILDS, it will cause failures if
.BR git\-rebase (1)
does not apply cleanly. The user is expected to fix those issues
before continuing.
.PP
More importantly, it may inadvertently keep malicious commits that
Trusted Users have removed from the git history.
.
.SH SEE ALSO
.ad l
.nh
.BR aur (1),
.BR aur\-depends (1),
.BR git (1),
.BR git\-clone (1),
.BR git\-config (1),
.BR git\-diff (1),
.BR git\-fetch (1),
.BR git\-log (1),
.BR git\-pull (1),
.BR git\-reset (1),
.BR git\-rev\-parse (1),
.BR git\-update\-ref (1)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
.
.\" vim: set textwidth=72:
