.TH AUR-SEARCH 1 2018-03-19 AURUTILS
.SH NAME
aur\-search \- search for AUR package

.SH SYNOPSIS
.SY "aur search"
.OP \-aisdmnqv
.OP \-k key
.IR keyword ...
.YS

.SH DESCRIPTION
\fBaur\-search\fR searches the AUR by multiple strings of packages. The
union of all results is returned. By default, searches are performed
by name and description using the \fIsearchby\fR interface, and
displayed in a brief format.

.SH OPTIONS

.TP
.B \-q ", " \-\-short
Only display package name, version and description.

.TP
.B \-v ", " \-\-verbose
Display more package information.

.TP
.B \-i ", " \-\-info
Use the \fIinfo\fR interface instead of \fIsearchby\fR.

.TP
.B \-d ", " \-\-desc
Search by package name and description.

.TP
.B \-m ", " \-\-maintainer
Search by maintainer.

.TP
.B \-n ", " \-\-name
Search by package name.

.TP
.B \-\-depends
Search for packages with keywords in \fBdepends\fR.

.TP
.B \-\-makedepends
Search for packages with keywords in \fBmakedepends\fR.

.TP
.B \-\-optdepends
Search for packages with keywords in \fBoptdepends\fR.

.TP
.B \-\-checkdepends
Search for packages with keywords in \fBcheckdepends\fR.

.TP
.BI "\-k " key
Sort results via a key, defaulting to \fIName\fR.

Possible choices are \fIName\fR, \fIVersion\fR, \fINumVotes\fR,
\fIDescription\fR (for brief output) or \fIName\fR, \fIPackageBase\fR,
\fIVersion\fR, \fIDescription\fR, \fIURL\fR, \fINumVotes\fR,
\fIPopularity\fR, \fIOutOfDate\fR, \fIMaintainer\fR,
\fIFirstSubmitted\fR, \fILastModified\fR (for \fB-v\fR verbose output).

.SH SEE ALSO
.BR aur (1),
.BR aur\-rpc (1),
.BR jq (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
