.TH AUR-DEPENDS 1 2022-07-03 AURUTILS
.SH NAME
aur\-depends \- retrieve dependencies using aurweb
.
.SH SYNOPSIS
.SY "aur depends"
.OP \-abGnt
.IR "pkgname [pkgname...]"
.YS
.
.SH DESCRIPTION
.B aur\-depends
solves dependencies for packages provided on the command line using
aurweb. The transitive closure of dependencies within AUR is computed.
.
.SH OPTIONS
.TP
.BR \-b ", " \-\-pkgbase
Print dependency information (AUR-only) to stdout as
.BR pkgbase ,
in total order.
.
.TP
.BR \-n ", " \-\-pkgname
Print dependency information (AUR-only) to stdout as
.BR pkgname ,
in total order.
.
.TP
.BR \-a ", " \-\-pkgname\-all
Print dependency information to stdout as
.BR pkgname ,
in total order. Direct
.BR pacman (8)
dependencies of one or more AUR dependencies
are included.
.
.TP
.BR \-G ", " \-\-graph
Print dependency information to stdout as edges
.BR \%pkgbase\etdepends ,
where
.I depends
is resolved to
.BR pkgbase .
.
.TP
.BR \-t ", " \-\-table
Output dependency information in the following format:
.BR \%pkgname\etdepends\etpkgbase\etpkgver .
.
.SS Dependency options
When resolving dependencies,
.B aur\-depends
considers all types (
.IR depends ,
.IR makedepends ,
and
.IR checkdepends )
of dependencies by default.
.I optdepends
can be taken into account with the
.BR \-\-optdepends
option. Types can be removed selectively with
the
.BR \-\-no\-depends ,
.BR \-\-no\-makedepends ,
and
.B \-\-no\-checkdepends
options. In particular, these options may be used to bypass cycles
between dependencies of differing types.
.
.SH NOTES
Version information is ignored for dependencies. See
.B FS#54906
for details.
.
.SH SEE ALSO
.ad l
.nh
.BR aur (1),
.BR aur\-graph (1),
.BR aur\-query (1),
.BR jq (1)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
.
.\" vim: set textwidth=72:
