.TH AUR-GRAPH 1 2018-05-05 AURUTILS
.SH NAME
aur\-graph \- print package/dependency directed graph

.SH SYNOPSIS
.SY "aur graph" .SRCINFO [.SRCINFO...]
.YS

.SH DESCRIPTION
.B aur\-graph
takes package information from
.B. SRCINFO
files and prints them as
.I pkgbase<TAB>dependency
pairs. Any dependencies are converted from
.B pkgname
to
.BR pkgbase ,
or skipped if absent from the input.

.SH EXAMPLES
The paired output is suitable as input for
.BR tsort (1),
provided no cycles are present. For example:
.EX

  $ cd ~/.cache/aurutils/sync
  $ aur graph */.SRCINFO | tsort | tac

.EE

.B .SRCINFO
files may be concatenated before processing to improve performance:
.EX

  $ cat */.SRCINFO | aur graph | tsort | tac

.EE

.B provides
and versioned dependencies are fully supported. This
may be used to verify dependency chains from
.BR aur\-depends (1).
For example:
.EX

  aur sync --print <package> | xargs printf '%s/.SRCINFO\n' | xargs aur graph

.EE

.SH SEE ALSO
.BR aur (1),
.BR aur\-depends (1),
.BR aur\-sync (1),
.BR awk (1),
.BR tsort (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
