.TH AUR-GRAPH 1 2018-05-05 AURUTILS
.SH NAME
aur\-graph \- package/dependency directed graph

.SH SYNOPSIS
.SY "aur graph" .SRCINFO [.SRCINFO...]
.YS

.SH DESCRIPTION
\fBaur-graph\fR takes package information from \fB.SRCINFO\fR files
and prints them as \fIpkgbase<TAB>dependency\fR pairs. Any
dependencies are converted from \fBpkgname\fR to \fBpkgbase\fR or
skipped if absent from the input.

.SH EXAMPLES
The paired output is suitable as input for \fBtsort(1)\fR, provided no
cycles are present. For example:
.EX

  cd ~/.cache/aurutils/sync
  aur graph */.SRCINFO | tsort | tac

.EE

\fB.SRCINFO\fR can be concatenated before processing to improve
performance:
.EX

  cat */.SRCINFO | aur graph | tsort | tac

.EE

\fBprovides\fR and versioned dependencies are fully supported. This
can be used to verify dependency chains from \fBaur-depends\fR(1). For
example:
.EX

  aur sync --print <package> | xargs printf '%s/.SRCINFO\n' | xargs aur graph

.EE

.SH SEE ALSO
.BR aur (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
