.TH AUR-REPO-FILTER 1 2018-05-05 AURUTILS
.SH NAME
aur\-repo\-filter \- filter packages in the Arch Linux repositories

.SH SYNOPSIS
.SY "aur repo-filter"
.OP \-a
.OP \-d database
.YS

.SH DESCRIPTION
\fBaur\-repo\-filter\fR checks if \fIpkgname\fR (provided on
\fIstdin\fR) is in the official Arch Linux repositories, and print it to
\fIstdout\fR if found. Virtual packages, when found, are solved and
printed to stderr.

.SH OPTIONS
.TP
.BI \-a ", " \-\-all
Query all available repositories. (\fBpacconf \-\-repo\-list\fR)

.TP
.B \-d \fINAME\fR ", " \-\-database=\fINAME\fR ", " \-\-repo=\fINAME\fR
Check a given repository. Multiple repositories can be specified by
repeating this argument.

.SH SEE ALSO
.BR aur (1),
.BR expac (1),
.BR jq (1),
.BR pacsift (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
