.TH AUR-REPO 1 2018-12-13 AURUTILS
.SH NAME
aur\-repo \- manage local repositories

.SH SYNOPSIS
.SY "aur repo"
.OP \-d database
.OP \-r root
.OP \-lSu
.OP \-\-repo\-list
.OP \-\-status\-file
.YS

.SH OPTIONS
.TP
.BI \-d " NAME" "\fR,\fP \-\-database=" NAME

.TP
.BI \-r " PATH" "\fR,\fP \-\-root=" PATH

.TP
.BR \-l ", " \-\-list

.TP
.BR \-u ", " \-\-updates

.TP
.BR \-S ", " \-\-sync

.TP
.BI \-\-status\-file= PATH

.TP
.BR \-\-repo\-list

.SH ENVIRONMENT

.B AUR_REPO
.RS
The repository used for building packages.  If
.B AUR_DBROOT
is not specified, the entry must be a valid
.B file://
repository configured in
.BR pacman.conf (5).
.RE

.SH SEE ALSO
.BR aur (1),
.BR expac (1),
.BR pacman (1),
.BR pacman.conf (5)
