.TH AUR.PKGLIST 1 2022-04-09 AURUTILS
.SH NAME
aur\-pkglist \- retrieve AUR metadata archives
.
.SH SYNOPSIS
.SY "aur pkglist"
.OP \-FP pattern
.OP \-bUqv
.OP \-I pattern
.OP \-S pattern
.OP \-t time
.YS
.
.SH DESCRIPTION
.B aur\-pkglist
retrieves metadata archives from the AUR. This includes plain-text lists of available
package names
.RB ( packages.gz ),
AUR users
.RB ( users.gz ),
and
package bases
.RB ( pkgbase.gz )
and JSON lists of all available metadata
.RB ( packages-meta-v1.json ,
.BR packages-meta-v1-ext.json ).
.PP
Metadata either matches the output of
.B search
or
.B info
type requests; see
.BR aur\-query (1).
A
.BR pcrepattern (3)
may be specified for plain-text lists, and a
.BR jq(1)
pattern for JSON lists.
.PP
If no options are specified,
.B aur\-pkglist
defaults to retrieving
.BR packages.gz .
.
.SH OPTIONS
.TP
.BR \-b ", " \-\-pkgbase
Retrieve
.B pkgbase.gz
instead of
.BR packages.gz .
.
.TP
.BR \-U ", " \-\-users
Retrieve
.B users.gz
instead of
.BR packages.gz .
.
.TP
.BR \-I ", " \-\-info
Retrieve AUR metadata from
.BR search \-type
requests. A
.BR jq (1)
pattern can be specified.
.
.TP
.BR \-S ", " \-\-search
Retrieve AUR metadata from
.BR info \-type
requests. A
.BR jq (1)
pattern can be specified.
.
.TP
.BI "\-F " pattern "\fR,\fP \-\-fixed\-strings " pattern
Interpret the given pattern as a list of fixed strings, separated by
newlines, any of which is to be matched.
.
.TP
.BI "\-P " pattern "\fR,\fP \-\-perl\-regexp " pattern
Interpret the given pattern as a Perl-compatible regular expression
(PCRE).
.
.TP
.BR \-q ", " \-\-quiet
Update the package list and print its path to standard output.
.
.TP
.BR \-t ", " \-\-time ", " \-\-ttl
Set the delay in seconds before a new list is retrieved.
Defaults to
.B 300
seconds.
.IP
.RS
.B Note:
.B aur\-pkglist
checks the HTTP
.I Last-Modified
property before retrieval. New lists are generated by the AUR every 5
minutes; setting a lower interval with
.B \-t
thus has no benefit.
.RE
.
.TP
.BR \-v ", " \-\-verify
Verify checksums of the compressed list with
.BR sha256sum (1).
.
.SH NOTES
See the following threads for more information about the development of AUR metadata archives:
.PP
.UR https://lists.archlinux.org/pipermail/aur-general/2021-November/036659.html
[aur\-general] New AUR Metadata Archives
.UE ,
.PP
.UR https://\:lists.archlinux.org/\:pipermail/\:aur-dev/\:2016-May/\:004036.html
[aur\-dev] Making the package list more useful
.UE .
.
.SH SEE ALSO
.ad l
.nh
.BR aur (1),
.BR aur\-query (1),
.BR curl (1),
.BR jq (1),
.BR pcregrep (1)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
.
.\" vim: set textwidth=72:
