.TH AUR-SYNC 1 2018-03-20 AURUTILS
.SH Name
aur\-sync \- download and build aur packages automatically

.SH SYNOPSIS
.SY "aur sync"
.OP \-AcfgLnprstu
.OP \-\-ignore
.OP \-\-no\-ver
.OP \-\-no\-ver\-shallow
.OP \-\-no\-view
.OP \-\-provides
.OP \-\-repo
.OP \-\-root
.OP \-\-
.IR pkgname ...
.OP \-
.YS

.SH DESCRIPTION
\fBaur\-sync\fR downloads and builds packages automatically to a local
repository. Package names serve as arguments.

If \fBvifm\fR(1) is installed, the downloaded files are shown using vifm
and can be edited. If not, the files are shown in \fBless\fR(1), or
\fI$PAGER\fR if configured.

.SH OPTIONS
.SS Build options
.TP
.BR \-f ", " \-\-force
Continue the build process if a package with the same name exists
already. (\fBaur build \-f\fR)

.TP
.B \-\-ignore=\fIPACKAGE\fR
Ignore a package upgrade. Multiple packages can be specified by
separating them with a comma, or by repeating the \fB\-\-ignore\fR option.

.TP
.BR \-\-nover ", " \-\-no\-ver
Disable version checking for packages in the queue.

.TP
.BR \-\-nover\-shallow ", " \-\-no\-ver\-shallow
Disable version checking for packages specified on the command line or
upgrade candidates from \-\-upgrades. Version checks for dependencies
remain enabled.

.TP
.BR \-p ", " \-\-print
Print target packages and their paths instead of building them.

.TP
.BR \-s ", " \-\-sign
Sign built packages and verify the database with gpg. (\fBaur build \-sv\fR)

.TP
.BR \-\-rebuild
Alias for \-f \-\-nover\-shallow.

.TP
.BR \-\-rebuildtree ", " \-\-rebuild\-tree
Alias for \-f \-\-nover.

.SS Container options
.TP
.BR \-c ", " \-\-chroot
Build packages with makechrootpkg. (\fBaur build \-c\fR)

.TP
.BR \-\-pacman\-conf=\fIFILE\fR
Set the \fIpacman.conf\fR file to be used in the container. (\fBaur
build \-C\fR)
.RE

.TP
.BR \-\-makepkg\-conf=\fIFILE\fR
Set the \fImakepkg.conf\fR file to be used in the container. (\fBaur
build \-M\fR)

.TP
.BR "\-D \fIDIR\fR" ", " \-\-directory=\fIDIR\fR
Set the container path to \fIDIR\fR. (\fBaur build \-D\fR)

.SS Download options
.TP
.B \-\-continue
Skip downloading package files.

.TP
.BR \-g ", " \-\-git
Clone AUR repositories with \fBgit-clone\fR(1).

.TP
.BR \-t ", " \-\-tar
Download AUR snapshots (\fIpkgbase.tar.gz\fR) and extract them with
\fBtar\fR(1).

.TP
.BR \-\-noview ", " \-\-no\-view
Do not view downloaded files before building.

.SS Repository options
.TP
.B \-\-list
List repository contents in a tab-separated format.

.TP
.B \-\-repo-list
Print all configured \fBfile://\fR repositories, together with their
file paths.

.TP
.BR \-\-noprovides ", " \-\-no\-provides
Do not take virtual dependencies (\fBprovides\fR) in the local
repository into account. Packages specified on the command line or
available upgrades are considered regardless of this setting.

.TP
.B \-d \fINAME\fR ", " \-\-database=\fINAME\fR ", " \-\-repo=\fINAME\fR
Use the \fINAME\fR repository. If this option is not specified,
\fBaur\-sync\fR defaults to the first \fIfile://\fR repository in
\fBpacman.conf\fR(5), or aborts if multiple are available.

.TP
.B \-\-root=\fIDIR\fR
The location of the repository root. Defaults to the \fIServer\fR
value of the configured repository.

.TP
.BR \-u ", " \-\-upgrades
Update all AUR packages in a local repository that are out-of-date.

.SS makepkg
The default set of options is \fBmakepkg \-crs\fR.

.TP
.BR \-A ", " \-\-ignorearch ", " \-\-ignore\-arch
Ignore a missing or incomplete \fIarch\fR field in the build script.
(\fBmakepkg \-A\fR)

.TP
.BR \-L ", " \-\-log
Enable logging to a text file in the build directory. (\fBmakepkg
\-L\fR)

.TP
.BR \-\-noconfirm ", " \-\-no\-confirm
Do not wait for user input. (\fBmakepkg \-\-noconfirm\fR)

.TP
.BR \-k ", " \-\-keep
Do not remove dependencies installed by makepkg.

.SS makechrootpkg
The default set of options is \fBmakechrootpkg \-cu\fR. For more information 
about building in containers, see \fBaur\-chroot\fR(1).

.TP
.B \-\-bind=\fIDIR\fR
Bind a directory read-only. (\fBmakechrootpkg \-D\fR)

.TP
.B \-\-bind-rw=\fIDIR\fR
Bind a directory read-write. (\fBmakechrootpkg \-d\fR)

.TP
.BR \-T ", " \-\-temp
Build in a temporary container. (\fBmakechrootpkg \-T\fR)

.SH ENVIRONMENT
.B AURDEST
.RS
Determines where build files will be cloned. This must be an absolute path.

Default: \fI$XDG_CACHE_HOME/aurutils/sync\fR
.RE

.B AURDEST_SNAPSHOT
.RS
Determines where build files will be copied when using snapshots
(\fBaur sync \-t\fR). This must be an absolute path.

Default: \fI$XDG_CACHE_HOME/aurutils/snapshot\fR
.RE

.B AUR_PAGER
.RS
The file manager used to view and edit build files. This variable is
split on white space, allowing \fIAUR_PAGER="program -option"\fR.
.RE

.B AUR_REPO
.RS
The repository used for building packages.
If \fBAUR_DBROOT\fR is not specified, then the entry must be a valid
\fBfile://\fR repository configured in \fBpacman.conf\fR(5).
.RE

.B AUR_DBROOT
.RS
The absolute path to the database corresponding to \fBAUR_REPO\fR.
.RE

.SH NOTES
Targets may be taken from stdin using \fBxargs\fR(1). For example:

.EX
  $ aur vercmp-devel | xargs aur sync --noconfirm
.EE

Note that command output interferes with input from the tty. The
\fB\-\-noconfirm\fR option may be used to disable interaction, or
output redirected to a file:

.EX
  $ aur vercmp-devel > new.txt
  $ xargs -a new.txt aur sync
.EE

When version checks are enabled (\fB\-\-no\-ver\fR is not specified),
build files are only retrieved if the remote (RPC) version is newer
than a version in the pacman database. Checks assume there are no
mismatches between \fB.SRCINFO\fR and \fBPKGBUILD\fR files.

Architecture-specific depends (as introduced with pacman 4.2) are
merged with regular depends in RPC queries. \fBaur\-sync\fR works around
this by stripping the \fIlib32\-\fR prefix from packages and removing
\fIgcc\-multilib\fR if the i686 architecture is detected.

\fItar\fR snapshots are extracted to the \fI$AURDEST_SNAPSHOT\fR
directory, in order to avoid conflicts with \fBgit\fR(1).

.SH SEE ALSO
.BR aur (1),
.BR aur\-build (1),
.BR aur\-fetch (1),
.BR aur\-rpc (1),
.BR aur\-repo\-filter (1),
.BR aur\-deps\-rpc (1),
.BR aur\-updates (1),
.BR jq (1),
.BR less (1),
.BR pacconf (1),
.BR vifm (1),
.BR pacman.conf (5)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
