.TH AUR-RFILTER 1 2017-10-04 AURUTILS
.SH NAME
aur-rfilter \- filter packages in the Arch Linux repositories

.SH SYNOPSIS
.SY aur
.B rfilter
.OP -d database
.YS

.SH DESCRIPTION
\fBaur\-rfilter\fR checks if \fIpkgname\fR (provided on \fIstdin\fR) is
in the official Arch Linux repositories, and print it to \fIstdout\fR if
not. Virtual packages, when found, are solved and printed to stderr.

.SH OPTIONS
.B \-d
.RS
Check a given repository instead of those from Arch Linux. Multiple
repositories can be specified by repeating \fB\-d\fR.
.RE

.SH SEE ALSO
.BR expac (1),
.BR pacsift (1),
.BR vercmp (1),
.BR aur (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
