.TH AUR.PKGLIST 1 2018-01-31 AURUTILS
.SH NAME
aur-pkglist \- print the AUR packagelist

.SH SYNOPSIS
.SY aur
.B pkglist
.OP \-bt
.OP \-FP pattern
.YS

.SH DESCRIPTION
\fBaur\-pkglist\fR prints the list of \fIpkgname\fRs that are available in the
AUR to standard output. Optionally a pattern can be specified that is
matched with \fBpcregrep\fR.

This list is available at:
.UR https://aur.archlinux.org/packages.gz
.UE

.SH OPTIONS
.B \-t
.RS
Set the delay in seconds before a new package list is retrieved.
Defaults to \fB300\fR seconds.
.RE

.B \-b
.RS
Retrieve \fIpkgbase.gz\fR instead of \fIpackages.gz\fR.
.RE

.B \-F
.RS
Interpret the given pattern as a list of fixed strings, separated by
newlines, any of which is to be matched.
.RE

.B \-P
.RS
Interpret the given pattern as a Perl-compatible regular expression
(PCRE).
.RE

.SH NOTES
To avoid retrieving the package list on every query, \fBaur\-pkglist\fR uses a
caching logic which stores the list together with its timestamp in
\fI$XDG_CACHE_HOME/aur\-pkglist\fR. New lists are generated every 5 minutes,
thus setting a lower interval with \fB\-t\fR yields no benefit.

See also:

.UR https://lists.archlinux.org/pipermail/aur-dev/2016-May/004036.html
[aur\-dev] Making the package list more useful
.UE

.SH SEE ALSO
.BR aur (1),
.BR gzip (1),
.BR pcregrep (1),
.BR wget (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
