.TH AUR-VERCMP 1 2018-02-01 AURUTILS
.SH NAME
aur\-vercmp \- check packages for AUR updates

.SH SYNOPSIS
.SY "aur vercmp"
.OP \-acq
.OP \-d repository
.OP \-p path

.SH OPTIONS
.TP
.B \-a
If \fB-c\fR is \fInot\fR specified, this option also shows packages with
older or the same version in the AUR. If specified twice, packages that
are not available in AUR are also shown.

.TP
.B \-c
Takes packages and their versions from stdin (\fIpkgname\fR as the first
field, \fIpkgver\fR as the second, both separated by tabs), printing
packages with equal or newer versions in a repository specified with
\fB\-d\fR to stdout. If this argument or \fB\-d\fR is \fInot\fR
specified, compare packages in the repository with their respective
versions in the AUR, and print updates to stdout.

.TP
.B \-d
The name of a pacman repository. If \fInot\fR specified, packages and their
versions are taken from stdin (tab-separated).

.TP
.B \-q
For all comparisons, show only package names.

.SH SEE ALSO
.BR aur (1),
.BR aur\-rpc (1),
.BR jq (1),
.BR pacman (1),
.BR vercmp (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
