.TH AUR-VERCMP 1 2018-12-06 AURUTILS
.SH NAME
aur\-vercmp \- check packages for AUR updates

.SH SYNOPSIS
.SY "aur vercmp"
.OP \-acq
.OP \-p path

.SH OPTIONS
.TP
.B \-a
If
.B \-c
is
.I not
specified, this option also shows packages with older or the same
version in the AUR. If specified twice, packages that are not
available in AUR are also shown.

.TP
.B \-c
Takes packages and their versions from stdin
.RI ( pkgname
as the first field,
.I pkgver
as the second, space-separated), printing packages with equal or newer
versions to stdout.

If this argument is
.I not
specified, compare packages in the repository with their respective
versions in the AUR, and print updates to stdout.

.TP
.B \-p
Read package versions from a file instead of the AUR. The package list should
be in the same format as stdin
.RI ( pkgname
as the first field,
.I pkgver
as the second, space-separated).

.TP
.B \-q
For all comparisons, show only package names.

.SH SEE ALSO
.BR aur (1),
.BR aur\-rpc (1),
.BR jq (1),
.BR pacman (1),
.BR vercmp (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
