.TH AURBUILD 1 2016-04-18 AURUTILS
.SH NAME
aurbuild \- build packages to a local repository

.SH SYNOPSIS
.SY aurbuild
.OP \-cs
.OP \-a queue
.OP \-d database
.OP \-p pool
.OP \-r root
.OP \--
.OP "makepkg args"
.YS

.SH DESCRIPTION
Build packages, adding the results to a local repository (a repository
configured with a \fIfile:// \fRprefix \fRin \fIpacman.conf\fR).

It is assumed that build directories are located in the current
directory, and described in a text file which is taken as argument.

.SH OPTIONS
All arguments after -- are passed to \fImakepkg\fR, or
\fImakechrootpkg \fRwhen \fI-c \fRis specified.

.B \-a
.RS
A text file with directories containing a PKGBUILD.
.RE

.B \-c
.RS
Build packages with \fImakechrootpkg\fR.
.RE

.B \-d
.RS
The name of the database.
.RE

.B \-p
.RS
The pool for the built packages. The \fBpool \fRis the location where
aurbuild will put the packages after building.
.RE

.B \-r
.RS
The root for the repository where the database files will live.
.RE

.B \-s
.RS
Sign built packages and the database with gpg.
.RE

.SH NOTES
It is recommended to use a pacman cache directory (\fICacheDir\fR) as
the package pool. This avoids checksum mismatches between built
packages, and any cached versions.

When building locally (outside a container), \fIpacman -Syu \fR is
run while restricted to a local repository. This is comparable to
\fImakepkg -i\fR, but without subsequent package installation (if a
package was installed before, it is updated to the latest available
version). An interesting side-effect is that pacman considers packages
inside the official repositories "local", and warns if they are newer
than any custom counterpart.

When building with makechrootpkg, the mirrorlist is updated to match
the current system, and the container is fully upgraded (\fIpacman
-Syu\fR). Changes to the pacman database are \fBnot \fRpropagated to
the local system; packages must be installed and updated separately,
typically through \fIpacman -Syu <package_name>\fR.

aurbuild itself makes no assumption on the \fIfile://\fR prefix, though
the repository pool and root must be writeable by the calling user.

.SH SEE ALSO
.BR pacconf (1),
.BR pacman (1),
.BR repose (1),
.BR makepkg.conf (5),
.BR pacman.conf (5),
.BR aurutils (7),
.BR makepkg (8)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
