.TH AURBUILD 1 2016-04-18 AURUTILS
.SH NAME
aurbuild \- build packages to a local repository
.
.SH SYNOPSIS
.SY aurbuild
.OP \-c
.OP \-a queue
.OP \-d database
.OP \-p pool
.OP \-r root
.OP \--
.OP "makepkg args"
.YS
.
.SH DESCRIPTION
Build packages, adding the results to a local repository (a repository
configured with a \fIfile:// \fRprefix \fRin \fIpacman.conf\fR).
.P
It is assumed that build directories are located in the current
directory, and described in a text file which is taken as argument.
.
.SH OPTIONS
.B \-a
.RS
A text file with directories containing a PKGBUILD.
.RE
.
.B \-c
.RS
Build packages with \fImakechrootpkg\fR.
.RE
.
.B \-d
.RS
The name of the database.
.RE
.
.B \-p
.RS
The pool for the built packages. The \fBpool \fIis the location where
aurbuild will put the packages after building.
.RE
.
.B \-r
.RS
The root for the repository where the database files will live.
.RE
.P
All arguments after -- are passed to \fImakepkg\fR, or
\fImakechrootpkg \fRwhen \fI-c \fRis specified.
.
.SH NOTES
It is recommended to use a pacman cache directory (\fICacheDir\fR) as
the package pool. This avoids checksum mismatches between built
packages, and any cached versions.
.
.SH SEE ALSO
.BR pacconf (1),
.BR pacman (1),
.BR repose (1),
.BR makepkg.conf (5),
.BR pacman.conf (5),
.BR makepkg (8)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
