.TH AURCHECK 1 2016-05-28 AURUTILS
.SH NAME
aurcheck \- check repository packages for AUR updates

.SH SYNOPSIS
.SY aurcheck
.OP \-aq repository

.SH OPTIONS
.B \-a
.RS
Also show packages which are newer, or of the same version, in the
target repository.
.RE

.B \-q
.RS
Only show package names.
.RE

.SH SEE ALSO
.BR aursearch (1),
.BR jq (1),
.BR pacman (1),
.BR vercmp (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
