.TH AURCHAIN 1 2016-04-24 AURUTILS
.SH NAME
aurchain \- solve and order dependencies using the aur rpc

.SH SYNOPSIS
.SY aurchain
.OP \-a
.OP pkgname
.OP pkgname...
.YS

.SH DESCRIPTION
aurchain takes package names and then solves and orders the
dependencies for those packages using the AUR RPC interface.

.SH OPTIONS
.B \-a
.RS
Print the full dependency tree, instead of only AUR packages.
.RE

.SH SEE ALSO
.BR curl (1),
.BR datamash (1),
.BR jq (1),
.BR tsort (1),
.BR aurutils (7)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
