.TH AURCHECK 1 2016-12-28 AURUTILS
.SH NAME
aurcheck \- check packages for AUR updates

.SH SYNOPSIS
.SY aurcheck
.OP \-aq
.OP \-d repository

.SH OPTIONS
.B \-a
.RS
Also show packages which are older or of the same version.
.RE

.B \-d
.RS
The name of the pacman database. If no database is specified, packages
and their versions are taken from stdin (\fIpkgname\fR as the first
field, \fIpkgver\fR as the second, both separated by blanks).
.RE

.B \-q
.RS
Only show package names.
.RE

.SH SEE ALSO
.BR aursearch (1),
.BR jq (1),
.BR pacman (1),
.BR vercmp (1)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
