.TH AURCHAIN 1 2017-04-14 AURUTILS
.SH NAME
aurchain \- solve and order dependencies using the aur rpc

.SH SYNOPSIS
.SY aurchain
.OP \-at
.OP pkgname...
.YS

.SH DESCRIPTION
aurchain takes package names and then solves and orders the
dependencies for those packages using the AUR RPC interface.

.SH OPTIONS
.B \-a
.RS
Print the full dependency tree, instead of only AUR packages.
.RE

.B \-t
.RS
Copy retrieved JSON files to a specified directory.
.RE

.SH NOTES
Version information is ignored for dependencies. See \fIFS#54096\fR.

.SH SEE ALSO
.BR aursearch (1),
.BR jq (1),
.BR tsort (1),
.BR aurutils (7)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
