.TH AURQUEUE 1 2016-04-18 AURUTILS
.SH NAME
aurqueue \- order dependencies using .SRCINFO files
.
.SH SYNOPSIS
.SY aurqueue
.OP pkgbase
.OP pkgbase...
.YS
.
.SH DESCRIPTION
aurqueue takes the names of packages and orders the dependency chains
using tsort.
.P
It is assumed that source directories are already available, and that
\fIaurqueue \fRis used in the same directory as those source directories.
.
.SH SEE ALSO
.BR datamash (1),
.BR find (1),
.BR tsort (1)
.
.SH AUTHORS
.MT https://github.com/AladW)
Alad Wenter
.ME

