.TH AURSEARCH 1 2016-05-18 AURUTILS
.SH NAME
aursearch \- search AUR package names by pcre pattern

.SH SYNOPSIS
.SY aursearch
.OP \-bqrv
.OP \-t seconds
.OP -F string
.I pattern
.YS

.SH DESCRIPTION
Search the AUR for packages. The argument is a PCRE pattern which is
matched against the AUR.

.SH OPTIONS
.B \-F
.RS
Search for a fixed string instead of a PCRE pattern.
.RE

.B \-b
.RS
Match pkgbase instead of pkgname.
.RE

.B \-q
.RS
Only display package names.
.RE

.B \-r
.RS
Output JSON from AUR RPC.
.RE

.B \-t
.RS
Set the delay before the package list is updated. (default: 5 minutes)
.RE

.B \-v
.RS
Display more package information.
.RE

.SH NOTES
As the AUR RPC is limited to GET requests, queries are split by 150
arguments to avoid HTTP 414 errors (FS#49089). The results are merged
to a single JSON structure.

PCRE searches are done by matching a pattern against
\fIpackages.gz\fR, and querying the result with the RPC. This is done
as the AUR itself has no regex support (FS#49099).

aurweb generates \fIpackages.gz \fRevery 5 minutes, so setting the
delay to a lower value has no benefit.

.SH SEE ALSO
.BR aria2c (1),
.BR curl (1),
.BR jshon (1),
.BR pcrepattern (3),
.BR aurutils (7)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
