.TH AURSEARCH 1 2016-05-18 AURUTILS
.SH NAME
aursearch \- search for AUR package

.SH SYNOPSIS
.SY aursearch
.OP \-imnrRv
.OP \-k key
.I package
.OP package...
.YS

.SH DESCRIPTION
\fBaursearch\fR searches the AUR by multiple strings of packages. The
union of all results is returned. By default, searches are performed
by name and description using the \fIsearchby\fR interface, and
displayed in a brief format.

.SH OPTIONS

.B \-r
.RS
Output JSON from the AUR RPC.
.RE

.B \-R
.RS
Output JSON from the AUR RPC. (single JSON structure)
.RE

.B \-v
.RS
Display more package information.
.RE

.B \-i
.RS
Use \fImultiinfo\fR instead of \fIsearchby\fR.
.RE

.B \-m
.RS
Search by maintainer.
.RE

.B \-n
.RS
Search by package name.
.RE

.B \-k
.RS
Sort results via a key, defaulting to \fIName\fR.

Possible choices are \fIName\fR, \fIVersion\fR, \fINumVotes\fR,
\fIDescription\fR (for brief output) or \fIName\fR, \fIPackageBase\fR,
\fIVersion\fR, \fIDescription\fR, \fIURL\fR, \fINumVotes\fR,
\fIPopularity\fR, \fIOutOfDate\fR, \fIMaintainer\fR,
\fIFirstSubmitted\fR, \fILastModified\fR (for \fB-v\fR verbose output).
.RE

.SH NOTES
As the AUR RPC is limited to GET requests, queries are split by 150
arguments to avoid HTTP 414 errors (FS#49089).

.SH SEE ALSO
.BR curl (1),
.BR jq (1),
.BR aurutils (7)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
