.TH AURSYNC 1 2016-05-06 AURUTILS
.SH Name
aursync \- download and build aur packages automatically
.
.SH SYNOPSIS
.SY aursync
.OP \-c
.OP \-B newdir
.OP \-u
.OP \-dfIkLntTvw
.OP pkgname...
.YS
.
.SH DESCRIPTION
Download and build packages automatically to a local
repository. Package names serve as arguments.
.P
If \fIvifm \fRis installed, the downloaded files are shown using vifm and
can be edited. If not, the files are shown in \fIless\fR, or
\fI$PAGER\fR if configured.
.P
Each repository must have a corresponding \fICacheDir\fR, with the
trailing directory matching the repository name. See \fBaurutils(7)
\fR for details.
.
.SH OPTIONS
.B \-c
.RS
Build packages with makechrootpkg. (\fIaurbuild -c\fR)
.RE
.
.B \-d
.RS
Do not resolve dependencies.
.RE
.
.B \-k
.RS
Do not view downloaded files before building.
.RE
.
.B \-I
.RS
Skip package names in pacman's \fIIgnorePkg \fRdirective.
.RE
.
.B \-t
.RS
Download the PKGBUILDs using aria instead of git.
.RE
.
.B \-u
.RS
Update AUR packages in a selected local repository.
.RE
.
.B \-v
.RS
Disable version checking for packages in the queue.
.RE
.
.B \-w
.RS
Only download source files, do not build anything.
.RE
.
.SS makepkg
.P
.B \-f
.RS
Overwrite built packages. (\fImakepkg -f\fR)
.RE
.
.B \-L
.RS
Save makepkg output. (\fImakepkg -L\fR)
.RE
.
.B \-n
.RS
Do not wait for user input. (\fImakepkg --noconfirm\fR)
.RE
.
.SS makechrootpkg
.
.B \-B
.RS
Bind a directory read-only. (\fImakechrootpkg -D\fR)
.RE
.
.B \-n
.RS
Check a built package with namcap. (\fImakechrootpkg -n\fR)
.RE
.
.B \-T
.RS
Build in a temporary directory. (\fImakechrootpkg -T\fR)
.RE
.
.SH ENVIRONMENT
.B AURDEST
.RS
Determines where build files will be cloned (default:
\fI$XDG_CACHE_HOME/aursync\fR).
.RE
.P
.B TMPDIR
.RS
Parent directory for temporary files.
.RE
.
.SH NOTES
Version checks assume there are no mismatches between .SRCINFO and
PKGBUILD files.
.
.SH SEE ALSO
.BR aria2c (1),
.BR aurbuild (1),
.BR aurchain (1),
.BR aursearch (1),
.BR aursift (1),
.BR git (1),
.BR less (1),
.BR pacconf (1),
.BR repofind (1)
.BR vifm (1),
.BR pacman.conf (5)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
