.TH OFFICER 1 2016-12-19 AURUTILS
.SH NAME
officer \- run pacman only considering the official repositories

.SH SYNOPSIS
.SY officer
.OP options
.YS

.SH DESCRIPTION
\fBofficer\fR is a wrapper for pacman which generates a temporary
configuration file with only the official repositories. This
configuration is then used to run pacman with the arguments passed to
repoman.

.SH SEE ALSO
.BR pacman.conf (5),
.BR aurutils (7),
.BR pacman (8)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
