.TH REPOFIND 1 2016-08-19 AURUTILS
.SH NAME
repofind \- display information on file:// repositories

.SH SYNOPSIS
.SY repofind
.OP \-c <path>
.OP \-l
.OP \-p <repo>
.OP \-s
.YS

.SH OPTIONS
.B \-c
.RS
Canonicalize a given path, and check if it is writeable and a
directory.
.RE

.B \-l
.RS
Find and list all \fIfile:// \fR(local) repositories in \fIpacman.conf\fR,
together with the \fIServer \fRdirective.
.RE

.B \-p
.RS
Retrieve the path of a given repository, and check if it is writeable
and a directory.
.RE

.B \-s
.RS
Interactively select a local repository (implies \fI\-i\fR).
.RE

.SH SEE ALSO
.BR pacconf (1),
.BR makepkg.conf (5),
.BR pacman.conf (5),
.BR aurutils (7)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME

.\" vim: set textwidth=72:
