.TH REPOFIND 1 2016-04-18 AURUTILS
.SH NAME
repofind \- display information on file:// repositories

.SH SYNOPSIS
.SY repofind
.OP \-i
.OP \-s
.YS

.SH OPTIONS
.B \-i
.RS
Find and list all \fIfile:// \fR(local) repositories in \fIpacman.conf\fR,
together with the \fIServer \fRdirective.
.RE

.B \-s
.RS
Interactively select a local repository (implies \fI\-i\fR).
.RE

.SH SEE ALSO
.BR aursearch (1),
.BR pacconf (1),
.BR makepkg.conf (5),
.BR pacman.conf (5)

.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
