#!/bin/bash
tmp=$(mktemp -d) || exit
trap 'rm -rf -- "$tmp"' EXIT

out=$(env -C "$tmp" aur fetch aurutils aurutils-git)
err=$?

# expected: cloned repositories (x2), exit 0
(( err == 0 )) && [[ -d $tmp/aurutils/.git ]] && [[ -d $tmp/aurutils-git/.git ]]
