#!/bin/bash -e
tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[custom]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

cat >"$tmp"/PKGBUILD <<EOF
pkgname=foo
pkgver=1
pkgrel=1
arch=('any')

package() {
    true
}
EOF

# create local repository
repo-add "$tmp"/custom.db.tar

# issue 513: PKGDEST (environment) should be ignored
cd "$tmp"
PKGDEST=/does/not/exist aur build -d custom --pacman-conf "$tmp"/pacman.conf
