.PHONY: chroot package match random regex root

chroot:
	@$(CURDIR)/aurutils.t $@

package:
	@$(CURDIR)/aurutils.t $@

match:
	@$(CURDIR)/aurutils.t $@

random:
	@$(CURDIR)/aurutils.t $@

regex:
	@$(CURDIR)/aurutils.t $@

root:
	@$(CURDIR)/aurutils.t $@
