.PHONY: chroot package random regex

chroot:
	@$(CURDIR)/aurutils.t $@

package:
	@$(CURDIR)/aurutils.t $@
	@$(CURDIR)/aurutils.t match
	@$(CURDIR)/aurutils.t root

random:
	@$(CURDIR)/aurutils.t $@

regex:
	@$(CURDIR)/aurutils.t $@
