#!/bin/bash
var_tmp=$(mktemp -d --tmpdir="${TMPDIR:-/var/tmp/}") || exit
trap 'rm -rf -- "$var_tmp"' EXIT

cat >"$var_tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[custom]
SigLevel = Optional TrustAll
Server = file://$var_tmp
EOF

# create local repository
repo-add "$var_tmp"/custom.db.tar || exit

test_packages=(
    'python-pyalsaaudio' # split packages - independent
    'fasm-linux-git' 'hnwatch' # split packages - pkgbase does not match pkgname
    'ros-build-tools' # empty make/depends
    'curr' # dependency order (#414)
    'mingw-w64-gcc-base' # cyclic dependencies - required removal of makedeps
    'gimp-plugin-separate+' # Special characters
)

test_packages_big=(
    'clion' # split package - multiple packages from same package base
    'libc++' 'libc++-abi' # split package - depends on package from same package base
    'openrct2-git' # make/depends_arch
    'plasma-git-meta' # 100+ depends
    'ros-lunar-desktop' # 250+ depends 
)

for p in "${test_packages[@]}"; do
    { aur sync --rmdeps --no-confirm --no-view --repo=custom --margs --skippgpcheck --pacman-conf "$var_tmp"/pacman.conf "$p" && \
	    pacman -Si --config "$var_tmp"/pacman.conf custom/"$p"; } || exit
done
