#!/bin/bash
# Can he fix it?
set -o pipefail

confirm() {
    local -l reply
    local message=$*

    read -rp "$message [Y/n] " reply
    [[ ! $reply || $reply = y?(es) ]]
}

if aurchain "$@" | tee queue | aurclone; then
    if confirm 'Inspect build files?'; then
        xargs -a queue -i find {} -maxdepth 1 | vifm - -c '+vie'
    fi

    aurbuild queue
fi
