#!/bin/bash
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -e

readonly argv0=aurbuild
readonly pwd=$PWD

makepkg_args=(-Lsc --holdver)

build_local() {
    ((sysupgrade)) && sudo pacman -Syu
    
    PKGDEST="$pool" LC_MESSAGES=C makepkg "${makepkg_args[@]}"
    repose -vf "$database" -r "$root" -p "$pool"
    sudo pacsync "${database%.*}"
}

build_chroot() {
    declare CHROOT=/var/lib/aurbuild

    if [[ ! -d $CHROOT/root ]]; then
	sudo mkdir -p "$CHROOT"
	sudo mkarchroot -C /etc/pacman.conf "$CHROOT"/root base base-devel
    fi

    sudo -E PKGDEST="$pool" makechrootpkg -d "$pool" -c -u -r "$CHROOT" -- --skippgpcheck
    repose -vf "$database" -r "$root" -p "$pool"
}

trap 'exit' INT

source /usr/share/makepkg/util.sh

[[ -t 2 ]] && colorize

while getopts :cd:f:p:r:y OPT; do
    case $OPT in
	c|+c) build=build_chroot ;;
	d|+d) database="$OPTARG" ;;
	f|+f) makepkg_args+=(-f) ;;
	p|+p) pool="$OPTARG" 	 ;;
	r|+r) root="$OPTARG" 	 ;;
	y|+y) sysupgrade=1       ;;
	*) plain "usage: $argv0 [+-cd ARG] [+-f ARG] [+-p ARG] [+-r ARG] [+-y} [--] ARGS..."
	   exit 1 ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if [[ ! $database ]] || [[ ! $pool ]] || [[ ! $root ]]; then
    error "Incomplete arguments (-d, -p, -r)"
    exit 1
fi

if [[ ! -f $1 ]]; then
    error "$1: No such file or directory"
    exit 2
fi

# Read from FD 3 to choose providers with makepkg (#21)
exec 3< "$1"

while read -r -u 3 p; do
    if cd "$pwd/$p"; then
	"${build:-build_local}"
    fi
done

exec 3<&-

# vim: set sw=4 sts=4:
