#!/bin/bash
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

set -o pipefail

confirm() {
    local -l reply
    local message=$*

    read -rp "$message [Y/n] " reply
    [[ ! $reply || $reply = y?(es) ]]
}

if aurchain "$@" | tee queue | aursync; then
    if confirm 'Inspect build files?'; then
        xargs -a queue -i find {} -maxdepth 1 | vifm - -c '+vie'
    fi

    aurbuild queue
fi
