#!/bin/bash
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

readonly argv0=aurchain

count() {
    jshon -F "$1" -Qe resultcount
}

deps() {
    jshon -F "$1" -Qe results -a -e Depends -a -u
    jshon -F "$1" -Qe results -a -e MakeDepends -a -u
    jshon -F "$1" -Qe results -a -e CheckDepends -a -u
}

pair() {
    for ((i = 0; i < "$1"; ++i)); do
	awk 'NR == 1 { p = $1 } NR > 1 { print p, $0 }' \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -upe Depends -a -u) \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -upe MakeDepends -a -u) \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -upe CheckDepends -a -u)
    done
}

url() {
    local str='https://aur.archlinux.org/rpc.php/rpc/?v=5&type=info'

    while read -r p; do
	str+="&arg[]=$p"
    done

    printf '%s' "$str"
}

query() {
    local start=$SECONDS

    if ! curl --retry 3 -sSgL "$(printf '%s\n' "$@" | tee copy | url)" > raw_0; then
        exit 1
    fi

    if [[ $(count raw_0) == 0 ]]; then
        error "No packages found"
        exit 1
    fi

    for ((a = 1; a <= 100; ++a)); do
	if ! curl --retry 3 -sSgL "$(deps raw_"$((--a))" | tee -a copy | url)" > raw_$a; then
	    exit 1
	fi

        if [[ $(count raw_$a) == 0 ]]; then
	    break
	fi
    done

    if ((a > 100)); then
	error "Total requests: $((++a)) (exceeded maximum)"
	exit 1
    else
	msg2 "Total requests: $((++a))"
	msg2 "Time: $((SECONDS - start)) seconds"
    fi
}

source /usr/share/makepkg/util.sh || exit 1

if ((!$#)); then
    error "usage: $argv0 package [package, ...]"
    exit 1
fi

[[ -t 2 ]] && colorize

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

# Check if tmp is not empty, as cd '' returns 0
if ! { [[ $tmp ]] && cd "$tmp"; }; then
    exit 1
fi

msg 'Querying AUR RPC...'
query "$@"

msg 'Generating dependencies...'
if curl --retry 3 -sSgL "$(sort -u < copy | url)" > raw_n; then
    pair "$(count raw_n)" raw_n | tsort > all
    jshon -F raw_n -e results -a -e Name -u > aur
    grep -Fxf aur all | tac
fi
