#!/bin/bash
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

argv0=aurchain
tmp=$(mktemp -d) || exit

readonly argv0 tmp

count() {
    jshon -F "$1" -Qe resultcount
}

deps() {
    awk -v FS='[<=>]' '{print $1}' \
    <(jshon -F "$1" -Qe results -a -e Depends -a -u) \
    <(jshon -F "$1" -Qe results -a -e MakeDepends -a -u) \
    <(jshon -F "$1" -Qe results -a -e CheckDepends -a -u)
}

pair() {
    for ((i = 0; i < "$1"; ++i)); do
	awk 'NR == 1 { p = $1 } NR > 1 { print p, $0 }' \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -u -p -e Depends -a -u) \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -u -p -e MakeDepends -a -u) \
	<(jshon -F "$2" -Qe results -e "$i" -e Name -u -p -e CheckDepends -a -u)
    done
}

request() {
    pair "$(count "$1")" "$1" | tsort | tac > deps

    while read -r pkgname pkgbase; do	
	if [[ $pkgname != $pkgbase ]]; then
	    sed -i "s|^$pkgname$|$pkgbase|g" deps
	fi
    done < <(jshon -F "$1" -e results -a -e Name -u -p -e PackageBase -u | xargs -n2)

    grep -Fxf <(jshon -F "$1" -e results -a -e PackageBase -u) deps | awk '{if (!seen[$1]++) print $1}'
}

url() {
    local str='https://aur.archlinux.org/rpc.php/rpc/?v=5&type=info'

    while read -r p; do
	str+="&arg[]=$p"
    done

    printf '%s' "$str"
}

chain() {
    if ! curl --retry 3 -sSgL "$(printf '%s\n' "$@" | tee copy | url)" > raw_0; then
        exit
    fi

    if [[ $(count raw_0) == 0 ]]; then
        error "No packages found"
        exit 2
    fi

    for ((a = 1; a <= 100; ++a)); do
	if ! curl --retry 3 -sSgL "$(deps raw_"$((--a))" | tee -a copy | url)" > raw_$a; then
	    exit
	fi

        if [[ $(count raw_$a) == 0 ]]; then
	    break
	fi
    done

    if ((a > 100)); then
	error "Total requests: $((++a)) (exceeded maximum)"
	exit 34
    fi
}

trap 'rm -rf "$tmp"' EXIT

source /usr/share/makepkg/util.sh || exit

[[ -t 2 ]] && colorize

if ((!$#)); then
    error "usage: $argv0 package [package, ...]"
    exit 1
fi

cd "$tmp" || exit

msg 'Querying AUR RPC...'
chain "$@"

msg 'Generating dependencies...'
if curl --retry 3 -sSgL "$(sort -u < copy | url)" > raw_n; then
    request raw_n
fi
