#!/bin/bash

readonly argv0=aurclone
readonly tmp=$(mktemp)

trap 'rm "$tmp"' EXIT

while read -r target; do
   ( if ! git clone -v https://aur.archlinux.org/"$target".git; then
        printf '%s\n' "$target 1" >> "$tmp"
     fi 
   ) &
done

wait

awk '{if($2 != 0) printf "Failed to clone: %s\n", $1}' < "$tmp" 2>/dev/null
