#!/bin/bash

readonly argv0=aurclone
readonly aurgit=https://aur.archlinux.org
readonly tmp=$(mktemp)

while read -r target; do
   ( if ! git clone -v "$aurgit/$target.git"; then
        printf '%s\n' "$target 1" >> "$tmp"
     fi 
   ) &
done

wait

awk '{if($2 != 0) printf "Failed to clone: %s\n", $1}' < "$tmp" 2>/dev/null

rm "$tmp"
