#!/bin/bash
# aurqueue - generate ordered dependency lists for package builds
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

set -o pipefail

# Determine the path to each .SRCINFO, outputs to stdout using using null
# delimitation.
findsrc() {
    find "$@" -maxdepth 1 -type f -name .SRCINFO -print0
}

# Use xargs to pass a list of paths to .SRCINFOs for processing, then
# outputs all (global) dependencies on stdout.
gendeps() {
    xargs -0i awk -v FS='[<=>]' '
    	  /pkgbase/			{name = $2; print $2, $2}
    	  /^\t(make|check)?depends/	{print name, $2}
	  /^$/                        	{nextfile}
    ' {}
}

# Ensure no packages are added to the output.
base() {
    grep -Fxf <(printf '%s\n' "$@")
}

if ! source /usr/share/makepkg/util.sh; then
    exit 1
fi

if ((!$#)); then
    error "usage: aurqueue repo [repo, ...]"
    exit 1
fi

[[ -t 2 ]] && colorize

msg "Generating dependencies..."
findsrc "$@" | gendeps | tsort | base "$@" | tac
