#!/bin/bash -e
# WARNING! ALL VOIDED WARRANTY IS VOIDED-ER IF YOU USE THIS SCRIPT! 

readonly cache="${XDG_CACHE_HOME:-$HOME/.cache}/aursearch"
readonly remote="https://aur.archlinux.org"
readonly rpc="$remote/rpc/?v=5&type=info"

filter() {
    tee # TBD
}

source /usr/share/makepkg/util.sh || exit 1

if ((!$#)); then
    error "aursearch: pattern"
    exit 1
fi

[[ -t 2 ]] && colorize

msg "Retrieving package list"
curl -sS "$remote"/packages.gz -o "$cache"/packages.gz -z "$cache"/packages.gz --create-dirs

msg "Collecting data"
while read -r p; do
    ((++i)); args+=("arg[]=$p")
    if ((i == 150)); then
    printf '%s\n' "${args[*]}" > tmp_"$((++t))"
        unset i args
    fi
done < <(zgrep -P -- "$1" "$cache"/packages.gz)
printf '%s\n' "${args[*]}" > tmp_"$((++i))"

msg "Sending request"
LC_COLLATE=C
while read -r -a tmp; do
    ((++r)); unset enc
    for a in "${tmp[@]}"; do
        enc+=(--data-urlencode "$a")
    done
    curl -sSgG --compressed "$rpc" "${enc[@]}" -o raw_"$r" &
done < <(cat ./tmp_*)
wait
