#!/bin/bash -e

readonly cache="${XDG_CACHE_HOME:-$HOME/.cache}/aursearch"
readonly remote="https://aur.archlinux.org"
readonly rpc="$remote/rpc/?v=5&type=info"

filter() {
    tee # TBD
}

split() {
    awk '!/#/ { if ((NR % 150) == 0) printf "%s\n", $0; else printf "%s ", $0; }'
}

source /usr/share/makepkg/util.sh || exit 1

if ((!$#)); then
    error "aursearch: pattern"
    exit 1
fi

[[ -t 2 ]] && colorize

msg "Retrieving package list"
curl -sS "$remote"/packages.gz -o "$cache"/packages.gz -z "$cache"/packages.gz --create-dirs

msg "Sending request"
while read -r -a tmp; do
    ((++line)); unset enc
    for pkg in "${tmp[@]}"; do
        enc+=(--data-urlencode "arg[]=$pkg")
    done
    curl -sSgG --compressed "$rpc" "${enc[@]}" -o raw_"$line" &
done < <(zgrep -P -- "$1" "$cache"/packages.gz | split)
wait
