#!/bin/bash
export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o pipefail

readonly argv0=aursync
readonly pwd=$PWD

confirm() {
    local -l reply
    local message=$*

    read -rp "$message [Y/n] " reply
    [[ ! $reply || $reply = y?(es) ]]
}

clone() {
    while read -r target; do
	if cd "$pwd/$target" 2>/dev/null; then
            if ! git pull -v; then
		return
            fi
	else
            if ! git clone -v https://aur.archlinux.org/"$target".git; then
		return
            fi
	fi
    done
}

if aurchain "$@" | tee queue | clone; then
    if confirm 'Inspect build files?'; then
        xargs -a queue -i find {} -maxdepth 1 | vifm - -c '+vie'
    fi
    aurbuild queue
fi

