#!/bin/bash
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -e -o pipefail

readonly aurweb=https://aur.archlinux.org

repofind() {
    declare repo
    declare -A rset

    for repo in $(pacconf --repo-list); do
	rset[$repo]=$(pacconf --single --repo="$repo" Server)

	if [[ ${rset[$repo]} =~ file:// ]]; then
	    printf '%s %s\n' "$repo" "${rset[$repo]}"
	fi
    done
}

reposelect() {
    declare repo server pool
    declare -A avail
    
    while read -r repo server; do
	avail[$repo]=$server
    done < <(repofind)

    if [[ ! ${avail[@]} ]]; then
	error "No file:// repository found"
        exit 2
    elif ((${#avail[@]} > 1)); then
	select repo in "${!avail[@]}"; do
	    break
	done
    else
	repo=${!avail[*]}
    fi

    pool=${avail[$repo]#file://}
    
    if [[ ! -d $pool ]] || [[ ! -w $pool ]]; then
	error "$pool: Directory is not writeable"
	exit 1
    fi

    msg2 "Using [$repo] repository"
    printf '%s %s\n' "$repo" "$pool"
}

quickcheck() {
    declare pkg ver args repo url="$aurweb/rpc.php/rpc/?v=5&type=info"
    declare -A set_l set_r

    if (($#)); then
	for pkg; do args+=(--name="$pkg"); done
    fi

    if read -r repo _ < <(reposelect); then
	while read -r pkg ver; do
	    set_l[$pkg]=$ver
	done < <(pacsift --repo="$repo" "${args[@]}" | ifne expac -S '%n %v' -)
    fi

    if [[ ${set_l[@]} ]]; then
	while read -r pkg ver; do
	    set_r[$pkg]=$ver
	done < <(aursearch -r "${!set_l[@]}" | jshon -e results -a -e Name -u -p -e Version -u | xargs -n2)
    else
	error "No packages available"
	exit 2
    fi
    
    for pkg in "${!set_r[@]}"; do
	if (($(vercmp "${set_r[$pkg]}" "${set_l[$pkg]}") == 1)); then
	    printf '%s\n' "$pkg ${set_l[$pkg]} -> ${set_r[$pkg]}"
	fi
    done
}

source /usr/share/makepkg/util.sh

[[ -t 2 ]] && colorize

while getopts :isu OPT; do
    case $OPT in
	i|+i) repofind   ;;
	s|+s) reposelect ;;
	u|+u) update=1   ;;	    
	*)    plain "usage: ${0##*/} [+-isu} [--] ARGS..."
	      exit 1 ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ((update)); then
    quickcheck "$@"
fi
