#!/bin/bash
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -e -o pipefail

findsrc() {
    find "$@" -maxdepth 1 -type f -name .SRCINFO -print0
}

gensrc() {
    xargs -0i awk '/^pkgbase/ {e = $3} /^\tsource/ {print e, $3}' {}
}

findvcs() {
    declare -A vcs match

    while IFS=':' read -r proto _ client; do
        vcs[$proto]=$client
    done < <(printf '%s\n' "${VCSCLIENTS[@]}")

    while read -r pkg uri; do
        proto=$(get_protocol "$uri")
        proto=${proto/[+:]*}
        
        if [[ ${vcs[$proto]} ]]; then
            match[$pkg]=${vcs[$proto]}
        fi
    done < <(findsrc "$@" | gensrc)

    for i in "${!match[@]}"; do
        printf '%s %s\n' "$i" "${match[$i]}"
    done
}

source /etc/makepkg.conf
source /usr/share/makepkg/util.sh

[[ -t 2 ]] && colorize

if ((!$#)); then
    plain "usage: vcsprepare target [target ...]"
    exit 1
fi

# 1. Retrieve "package client" strings from .SRCINFO
# 2. Install client if not available
# 3. Update VCS sources
# 4. Update .SRCINFO
while read -r pkg client; do
    if ! pacman -T "$client"; then
        sudo pacman -S --asdeps --noconfirm "$client"
    fi

    # XXX: Only works if targets are in PWD
    ( cd "$pkg"
      makepkg -do --noprepare
      makepkg --printsrcinfo > .SRCINFO
    )
done < <(findvcs "$@")
