#!/bin/bash
# create directory for log files
log=$(mktemp -d) || exit

exec {fd}> "$log"/xtrace
export BASH_XTRACEFD=$fd

set -o xtrace
export SHELLOPTS

# run program with redirected input/output
"$@" >"$log"/stdout 2>"$log"/stderr

# the resulting files should be uploaded
printf '%s\n' "$log"/{xtrace,stdout,stderr}
