#!/bin/bash
# create directory for log files
log=$(mktemp -d) || exit
exec {fd}> "$log"/xtrace

# run program with redirected input/output
env SHELLOPTS=xtrace BASH_XTRACEFD=$fd "$@" \
    >"$log"/stdout 2>"$log"/stderr

# the resulting files should be uploaded
printf '%s\n' "$log"/{xtrace,stdout,stderr}
