#!/bin/bash
set -e
tests_t=(json/{ascii,depends,meta,none,empty_a,search,utf-8}.json*)
tests_f=(json/{empty,error}.json)

for t in "${tests_t[@]}"; do
    # check if correct amount of entries were parsed
    cnt1=$(aur format -f '%n\n' "$t" | wc -l)

    # variable input formats
    u=${t%%.json}
    case ${u##json/} in
        ascii|depends|search|utf-8|none)
            cnt2=$(jq < "$t" '.results | length') ;;
        meta|empty_a)
            cnt2=$(jq < "$t" '. | length') ;;
        search.jsonl)
            cnt2=$(jq < "$t" -s 'map(.results | length) | add') ;;
    esac
    [[ $cnt1 == $cnt2 ]]
done

# error codes:
# 1: option error
# 2: file error
# 4: invalid input

# exit on invalid potion
aur format json/ascii.json --doesnotexit || err=$?
[[ $err == 1 ]]
aur format json/ascii.json || err=$?
[[ $err == 1 ]]

# exit >0 if file path does not exist
aur format -f '%n' /does/not/exist || err=$?
[[ $err == 2 ]]

# check for errors on invalid inputs
aur format -f '%n' json/error.json || err=$? # response error
[[ $err == 4 ]]

# check modes with empty stdin
printf '' | aur format -f '%n\n'
