#!/bin/bash
shopt -s extglob
shopt -s nullglob
export AUR_ASROOT=1

parse_loop() {
  awk '/^while true; do$/,/^done$/ {
    if ( $0 ~ /^\s*-.*)$/ && $1 != "--)" ) {  # match -<something>) except --)
      gsub(/[ )]/,"")                         # remove spaces and final parens
      split($0, patterns,"|")                 # split on |
      getline                                 # ask for next line for shift check
      for (i in patterns) {                   # print options accordingly
        if ($2 ~ /^optval/) {
          print patterns[i] "::"
        } else if ($1 ~ /^shift/) {
          print patterns[i] ":"
        } else {
          print patterns[i]
        }
      }
    }
  }'
}

ret=0
have_optdump=(aur-build aur-chroot aur-fetch aur-pkglist aur-repo aur-repo-filter aur-srcver aur-sync aur-vercmp aur-view)
for cmd in "${have_optdump[@]}"; do
      aurcmd=${BASH_SOURCE%/*}/../lib/$cmd

      diff --color -U0 --label "$aurcmd Options" --label "$aurcmd Loop" \
        <(bash --pretty-print -O extglob "$aurcmd" | parse_loop | sort) \
        <(AUR_DEBUG=1 command "$aurcmd" --dump-options 2>/dev/null | sort)
      ((ret|=$?))
done

exit $ret
