#!/bin/bash

# random position of stdin marker
cnt=$(aur query -t info aurutils aurutils-git - </dev/null | jq .resultcount)
(( cnt == 2 )) || exit
cnt=$(aur query -t info aurutils - aurutils-git </dev/null | jq .resultcount)
(( cnt == 2 )) || exit
cnt=$(aur query -t info - aurutils aurutils-git </dev/null | jq .resultcount)
(( cnt == 2 )) || exit

# concatenation of stdin and command-line arguments
cnt=$(aur query -t info aurutils - <<< 'aurutils-git' | jq .resultcount)
(( cnt == 2 )) || exit

# multiple stdin markers
cnt=$(aur query -t info - - aurutils </dev/null | jq .resultcount)
(( cnt == 1 )) || exit
cnt=$(aur query -t info - aurutils - </dev/null | jq .resultcount)
(( cnt == 1 )) || exit
cnt=$(aur query -t info aurutils - - </dev/null | jq .resultcount)
(( cnt == 1 )) || exit

# type is mandatory
aur query aurutils
(( $? == 1 )) || exit

# no arguments specified
aur query -t info
(( $? == 1 )) || exit
aur query -t info - </dev/null
(( $? == 0 )) || exit
