.TH AURBUILD 1 2016-04-18 AURUTILS
.SH NAME
aurbuild \- build packages to a local repository
.
.SH SYNOPSIS
.B aurbuild
.OP \-a queue
.OP \-c
.OP \-d database
.OP \-p pool
.OP \-r root
.OP \-- makepkg
.
.SH DESCRIPTION
Build a package from a text file with directory names and add the
resulting packages to a local repository. A local repository is a
repository on the local file system. It is configured using the
\fIfile:// \fRprefix for \fIServer \fRin pacman.conf.
.
.SH OPTIONS
.B \-a
.RS
A text file with directories that contain a PKGBUILD.
.RE
.
.B \-c
.RS
Build in an nspawn container.
.RE
.
.B \-d
.RS
The name of the database.
.RE
.
.B \-p
.RS
The pool for the built packages. The pool is the location where
aurbuild will put the packages after building.
.RE
.
.B \-r
.RS
The root for the repository where the database files will live.
.RE
.P
All arguments after -- are passed to makepkg, or makechrootpkg when
building in a chroot.
.
.SH SEE ALSO
.BR repose (1),
.BR pacconf (1),
.BR makepkg (8),
.BR pacman.conf (5)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
