.TH REPOMAN 1 2016-04-18 AURUTILS
.SH NAME
repoman \- run pacman only considering the official repositories
.
.SH SYNOPSIS
.SY repoman
.OP options
.YS
.
.SH DESCRIPTION
Repoman is a wrapper for pacman which generates a temporary
configuration file with only the official repositories. This
configuration is then used to run pacman with the arguments passed to
repoman.
.
.SH SEE ALSO
.BR pacman (8),
.BR pacman.conf (5)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
