.TH REPOFIND 1 2016-04-18 AURUTILS
.SH NAME
repofind \- display information on file:// repositories
.
.SH SYNOPSIS
.SY repofind
.OP \-is
.OP \-c repository
.OP \-u repository
.YS
.
.SH OPTIONS
.B \-c
.RS
Remove cached packages (usually in /var/cache/pacman/pkg) from a given
repository.
.RE
.
.B \-i
.RS
Find and list all file:// (local) repositories in pacman.conf
.RE
.
.B \-s
.RS
Interactively select a local repository and output the name and
location to stdout
.RE
.
.B \-u
.RS
Check for updates in the named repository
.RE
.
.SH SEE ALSO
.BR makepkg.conf (5),
.BR pacman.conf (5)
.
.SH AUTHORS
.MT https://github.com/AladW
Alad Wenter
.ME
