#!/bin/bash
# aur-sync - download and build AUR packages automatically
set -o errexit -o pipefail
shopt -s extglob
readonly argv0=sync
readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
readonly AURDEST=${AURDEST:-$XDG_CACHE_HOME/aurutils/$argv0}
readonly AURDEST_SNAPSHOT=${AURDEST_SNAPSHOT:-$XDG_CACHE_HOME/aurutils/snapshot}
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default arguments
build_args=()
fetch_args=()
makechrootpkg_args=(-cu)
makechrootpkg_makepkg_args=()
makepkg_args=(-cs)
repo_args=()

# default options (enabled)
build=1 chkver_depth=2 download=1 view=1 provides=0

# default options (disabled)
chroot=0 rotate=0 snapshot=0 update=0 keep_deps=0

lib32() {
    awk -v arch="$(uname -m)" '{
        if(arch == "i686") {
            gsub(/^lib32-/,"")
            gsub(/^gcc-multilib$/,"")
        }
        print
    }'
}

# files: $1 pkgname\tpkgbase $2 pkgname (order by $2)
select_pkgbase() {
    awk 'NR == FNR {
        map[$1] = $2
        next
    }
    $1 in map {
	base = map[$1]
	
	# only print pkgbase on first occurence
	if (base in seen) {
	    next
	} else {
	    print base
	    seen[base]
	}
    }' "$@"
}

# fields: $1 pkgname, $2 depends[<>=]
tr_ver() {
    awk -F'[<>=]' '{print $1}'
}

complement() {
    # empty set should not return 1
    grep -Fxvf "$@" || return $(($?-1))
}

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp" "$tmp_view"
    fi
}

usage() {
    plain "usage: $argv0 [-ABcDfglLnrstTu] [--] pkgname..." >&2
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

opt_short='C:d:D:M:AcfgkLnpPstTuh'
opt_long=('bind:' 'bind-rw:' 'database:' 'directory:' 'ignore:'
          'root:' 'makepkg-conf:' 'pacman-conf:' 'allan' 'chroot'
          'continue' 'force' 'ignore-arch' 'ignorearch' 'log'
          'noconfirm' 'no-confirm' 'no-ver' 'nover' 'nover-shallow'
          'no-ver-shallow' 'no-view' 'noview' 'print' 'provides'
          'rm-deps' 'keep' 'sign' 'temp' 'tar' 'upgrades' 'git'
          'rebuild' 'rebuildtree' 'rebuild-tree' 'help')
opt_hidden=('dump-options')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset pkg pkg_i
while true; do
    case "$1" in
        -d|--database)        shift; repo_args+=(-d "$1") ;;
        -D|--directory)       shift; build_args+=(-D "$1") ;;
        -M|--makepkg-conf)    shift; build_args+=(--makepkg-conf "$1") ;;
        -C|--pacman-conf)     shift; build_args+=(--pacman-conf "$1") ;;
        --bind)               shift; makechrootpkg_args+=(-D "$1") ;;
        --bind-rw)            shift; makechrootpkg_args+=(-d "$1") ;;
        --ignore)             shift; IFS=, read -a pkg -r <<< "$1"
                              pkg_i+=("${pkg[@]}") ;;
        --root)               shift; repo_args+=(-r "$1") ;;
        -A|--ignore?(-)arch)  makepkg_args+=(-A)
                              makechrootpkg_makepkg_args+=(-A) ;;
        -c|--chroot)          chroot=1; build_args+=(-c) ;;
        -f|--force)           build_args+=(-f) ;;
        -g|--git)             snapshot=0 ;;
        -L|--log)             makepkg_args+=(-L) ;;
        -P|--provides)        provides=1 ;;
        -k|--keep)            keep_deps=1 ;;
        -n|--no?(-)confirm)   makepkg_args+=(--noconfirm) ;;
        -p|--print)           build=0 ;;
        -t|--tar)             snapshot=1 ;;
        -s|--sign)            build_args+=(-sv) ;;
        -T|--temp)            makechrootpkg_args+=(-T) ;;
        -u|--upgrades)        update=1 ;;
        --allan)              rotate=1 ;;
        --continue)           download=0 ;;
        --no?(-)ver)          chkver_depth=0 ;;
        --no?(-)ver-shallow)  chkver_depth=1 ;;
        --no?(-)view)         view=0 ;;
        --rebuild)            build_args+=(-f); chkver_depth=1 ;;
        --rebuild?(-)tree)    build_args+=(-f); chkver_depth=0 ;;
        -h|--help) usage ;;
        --dump-options)       printf -- '--%s\n' "${opt_long[@]}" ;
                              printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g' ;
                              exit ;;
        --) shift; break ;;
    esac
    shift
done
unset opt_short opt_long OPTRET

tmp=$(mktemp -dt "$argv0".XXXXXXXX)
tmp_view=$(mktemp -dt view.XXXXXXXX)
trap 'trap_exit' EXIT

if ((rotate)); then
    if { hash rot13 && target=$(aur pkglist | shuf -n 1); } 2>/dev/null; then
        exec bash -c "{ aur \"$argv0\" -c \"$target\" && repo-elephant | rot13; } 2>&1 | rot13"
    else
        echo '?'; exit 16 # EBUSY
    fi
fi

if ! ((keep_deps)); then
    makepkg_args+=(-r)
fi

if ! (($# + update)); then
    error "$argv0: no targets specified"
    exit 1
fi

if ((snapshot)); then
    aur_workdir=$AURDEST_SNAPSHOT
    fetch_args=(-L "$tmp_view" -t)
else
    aur_workdir=$AURDEST
    fetch_args=(-L "$tmp_view" -g)
fi

mkdir -p "$aur_workdir"
cd_safe "$tmp"

# retrieve path to local repo (#448)
aur repo "${repo_args[@]}" --list --status-file=db >db_info

{ IFS= read -r db_name
  IFS= read -r db_root
} <db

if [[ -w $db_root/$db_name.db ]]; then
    msg "Using [$db_name] repository" >&2
else
    error "$argv0: $db_root/$db_name.db: permission denied"
    exit 13
fi

{ if (($#)); then
      printf '%s\n' "$@"
  fi

  if ((update)); then
      aur vercmp <db_info | cut -d: -f1
  fi
} >argv

if [[ -s argv ]]; then
    # $1 pkgname $2 depends $3 pkgbase $4 pkgver
    aur depends <argv >depends
else
    plain "there is nothing to do" >&2
    exit
fi

# $1 pkgname $2 pkgbase $3 pkgver
cut -f2 --complement depends | sort -u >pkginfo

{ if ((${#pkg_i[@]})); then
      printf >&2 'warning: ignoring %s package\n' "${pkg_i[@]}"
      printf '%s\n' "${pkg_i[@]}"
  fi

  # packages with equal or newer versions are taken as complement
  # for the queue. if chkver_shallow is enabled, packages on the
  # command-line are excluded from this complement
  if ((chkver_depth)); then
      case $chkver_depth in
          1) chkver_i() { complement argv; } ;;
          2) chkver_i() { tee; } ;;
      esac

      cut -f1,3 pkginfo | aur vercmp -p db_info -c | chkver_i
  fi

  if ((provides)); then
      # note: this uses pacman's copy of the repo (as used by makepkg -s)
      cut -f1 pkginfo | complement argv | aur repo-filter -d "$db_name"
  fi
} >filter

# pkgname queue (AUR + repos)
cut -f1,2 depends | tr_ver | tsort | tac | lib32 | complement filter >queue_0

# pkgbase queue (AUR)
cut -f1,2 pkginfo | select_pkgbase - queue_0 >queue

if [[ -s queue ]]; then
    cd_safe "$aur_workdir"
else
    plain "there is nothing to do" >&2
    exit
fi

if ((download)); then
    msg "Retrieving package files" >&2

    aur jobs -Xj +3 --nice 10 --halt soon,fail=1 \
        aur fetch "${fetch_args[@]}" :::: "$tmp"/queue
fi

# link build files in the queue (absolute links)
aur jobs -X ln -s "$(pwd -P)"/{} "$tmp_view" :::: "$tmp"/queue

if type -P >/dev/null vifm; then
    # avoid directory prefix in printed paths (#452)
    viewer() ( cd "$1"; vifm -c 'view!' -c '0' - )
else
    viewer() { command -- ${PAGER:-less -K}; }
fi

if ((view)); then
    if [[ -v AUR_PAGER ]]; then
        command -- $AUR_PAGER "$tmp_view"
    else
        { # print patch files
          find "$tmp_view" -maxdepth 1 -type f

          # print build directories in dependency order
          xargs -I{} -a "$tmp"/queue find -L "$tmp_view"/{} -maxdepth 1
        } | viewer "$tmp_view"
    fi
fi

if ((build)); then
    build_args+=(-a "$tmp"/queue -d "$db_name" -r "$db_root")

    # check if dependency graph is valid
    aur graph "$tmp_view"/*/.SRCINFO >/dev/null

    if ((chroot)); then
        aur build "${build_args[@]}" -- "${makechrootpkg_args[@]}" \
            -- "${makechrootpkg_makepkg_args[@]}"
    else
        aur build "${build_args[@]}" -- "${makepkg_args[@]}"
    fi
else
    xargs -a "$tmp"/queue -I{} printf '%s\n' "$(pwd -P)"/{}
fi

# vim: set et sw=4 sts=4 ft=sh:
