#!/bin/bash
# aur-fetch-git - retrieve build files using git
set -o errexit
readonly argv0=fetch-git
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

merge() {
    git fetch -v

    if [[ $(git rev-parse HEAD) != $(git rev-parse '@{upstream}') ]]; then
        git --no-pager log --patch --stat '..@{upstream}'

        # reset index and working tree
        git reset --hard HEAD
        git merge
    fi
}

merge_across_fs() {
    # avoid issues with filesystem boundaries (#274)
    GIT_DIR="$1"/.git GIT_WORK_TREE="$1" merge
}

usage() {
    printf -- 'usage: %s [-L log_dir]\n' "$argv0" >&2
    exit 1
}

unset log_dir
while getopts :L: opt; do
    case $opt in
        L) log_dir=$OPTARG ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if [[ -v log_dir ]] && [[ ! -d $log_dir ]]; then
    printf -- >&2 '%s: %q: not a directory\n' "$argv0" "$log_dir"
    exit 20
fi

if [[ -v log_dir ]]; then
    merge_log() { tee -a "$log_dir/$1".patch >/dev/null; }
else
    merge_log() { tee; }
fi

while IFS= read -r uri; do
    pkg=${uri##*/}   # strip path
    pkg=${pkg%%.git} # strip .git suffix

    if [[ -d $pkg/.git ]]; then
        merge_across_fs "$pkg" | merge_log "$pkg"
    else
        git clone "$uri"
    fi
done

# vim: set et sw=4 sts=4 ft=sh:
