#!/bin/bash
# aur-build - build packages to a local repository
set -o errexit
shopt -s extglob
readonly argv0=build
readonly startdir=$PWD
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default arguments
chroot_args=()
gpg_args=(--detach-sign --no-armor --batch)
makechrootpkg_args=(-cu)
makepkg_args=(-rs --noconfirm)
repo_add_args=()

# default options
chroot=0 no_sync=0 overwrite=0 sign_pkg=0

build_failure() {
    error "$argv0: failure on package $1"

    mapfile -tu "$2" pkg_todo
    printf >&2 'remaining packages: %s\n' "${pkg_todo[*]:-(none)}"

    mapfile -tu "$3" pkg_done
    printf >&2 'processed packages: %s\n' "${pkg_done[*]:-(none)}"

    exit "$4"
}

conf_single() {
    printf '[options]\n'
    pacconf --options --raw

    printf '[%s]\n' "$1"
    pacconf --repo="$1" --raw
}

db_replaces() {
    bsdcat "$1" | awk '/%REPLACES%/ {
        while(NF != 0) {getline; print}
    }'
}

find_pkg_dupes() {
    # This function uses the extended --packagelist introduced with
    # pacman 5.1. It assumes that PKGEXT does not change between
    # invoking --packagelist and makepkg in the later build process.
    makepkg --packagelist | xargs -I{} find "$1" -maxdepth 1 -name '{}'
}

print_quoted() {
    printf '%q\n' "$@"
}

trap_exit() {
    if ! [[ -o xtrace ]]; then
        rm -rf "$tmp" "$var_tmp"
    fi
}

usage() {
    plain "usage: $argv0 -d database [-afNRsv] [--] <makepkg args>"
    exit 1
}

source /usr/share/makepkg/util/util.sh
source /usr/share/makepkg/util/message.sh

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

tmp=$(mktemp -d "${TMPDIR:-/tmp}/$argv0".XXXXXXXX)
var_tmp=$(mktemp -d "${TMPDIR:-/var/tmp}/$argv0".XXXXXXXX)

trap 'trap_exit' EXIT
trap 'exit' INT

unset database db_root queue
while getopts a:d:r:C:D:M:cfNRsv opt; do
    case $opt in
        a) queue=$OPTARG    ;;
        c) chroot=1         ;;
        f) overwrite=1      ;;
        N) no_sync=1        ;;
        r) db_root=$OPTARG  ;;
        d) database=$OPTARG
           chroot_args+=(-d "$OPTARG") ;;
        C) chroot_args+=(-C "$OPTARG") ;;
        D) chroot_args+=(-D "$OPTARG") ;;
        M) chroot_args+=(-M "$OPTARG") ;;
        R) repo_add_args+=(-R) ;;
        s) sign_pkg=1
           repo_add_args+=(-s) ;;
        v) repo_add_args+=(-v) ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if [[ ${database=$AUR_REPO} ]]; then
    server=$(pacconf --single --repo="$database" Server)
    server=${server#*//}
else
    error "$argv0: database: missing argument"
    usage
fi

db_root=$(realpath -e -- "${db_root-$server}")
db_path=$(realpath -e -- "${db_root}/$database.db") # .db symbolic link to archive

if ! [[ -r $db_path && -w $db_path ]]; then
    error "$argv0: $db_path: permission denied"
    exit 13
fi

if [[ -v queue ]]; then
    exec {fd}< "$queue"
else
    exec {fd}< <(printf '\n')
fi

# keep track of processed packages (#264)
exec {fd_done}> "$tmp"/queue_processed

# reset default makechrootpkg arguments
if (($#)); then
    if ((chroot)); then
        makechrootpkg_args=("$@")
    else
        makepkg_args=("$@")
    fi
fi

if type -P xdelta3 >/dev/null; then
    repo_add_args+=(-d)
fi

if ((sign_pkg)); then
    if [[ -v GPGKEY ]]; then
        gpg --list-keys "$GPGKEY"
        gpg_args+=(-u "$GPGKEY")
    fi
else
    db_sigs=("$db_root/$database"{,.files}.sig)

    if [[ -f ${db_sigs[0]} ]]; then
        # avoid errors from stale db.sig files
        error "$argv0: database signature found, but signing is disabled"

        print_quoted >&2 "${db_sigs[@]}"
        exit 1
    fi
fi

if ((chroot)); then
    aur chroot -B "${chroot_args[@]}"
else
    conf_single "$database" >"$tmp"/custom.conf
fi

while IFS= read -ru "$fd" path; do
    cd_safe "$path"

    if ((!overwrite)); then
        mapfile -t mark < <(find_pkg_dupes "$db_root")

        if [[ ${mark[*]} ]]; then
            warning "$argv0: skipping built package (use -f to overwrite)"

            print_quoted >&2 "${mark[@]}"
            continue
        fi
    fi

    m_err=0
    if ((chroot)); then
        PKGDEST="$var_tmp" aur chroot -P "${chroot_args[@]}" \
            -- "${makechrootpkg_args[@]}" || m_err=$?
    else
        PKGDEST="$var_tmp" makepkg "${makepkg_args[@]}" || m_err=$?
    fi

    if ((m_err)); then
        build_failure "${path##*/}" "$fd" "$fd_done" "$m_err"
    fi

    cd_safe "$var_tmp"
    pkglist=(./!(*.sig)) # discard makepkg --sign from package list (#401)
    siglist=()

    for p in "${pkglist[@]}"; do
        if [[ -f $p.sig ]]; then
            warning "$argv0: existing package signature found"
            siglist+=("$p".sig)

        elif ((sign_pkg)); then
            gpg "${gpg_args[@]}" --output "$p".sig "$p"
            siglist+=("$p".sig)
        fi
    done

    # move build products (relative paths)
    mv -bf "${pkglist[@]}" "${siglist[@]}" "$db_root"

    cd_safe "$db_root"
    LANG=C repo-add "${repo_add_args[@]}" "$db_path" "${pkglist[@]}"

    basename "$path" >&"$fd_done"
    cd_safe "$startdir"

    if ((chroot)) || ((no_sync)); then
        continue
    else
        replaces=$(grep -Fxf <(db_replaces "$db_path") <(pacman -Qq) | paste -s -d, -)

        sudo pacman -Fy  --config="$tmp"/custom.conf
        sudo pacman -Syu --config="$tmp"/custom.conf --ignore="$replaces" --noconfirm
    fi
done

exec {fd}<&-

# vim: set et sw=4 sts=4 ft=sh:
