#!/bin/bash
# aur-rpc - interface with AurJson
readonly argv0=rpc
readonly AUR_LOCATION=${AUR_LOCATION:-'https://aur.archlinux.org'}
readonly PS4='+(${BASH_SOURCE}:${LINENO}):${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
readonly AUR_COLOR=${AUR_COLOR-auto}

# default options
declare -i rpc_ver=5
declare    rpc_url="$AUR_LOCATION/rpc/?v=$rpc_ver"

uri_info() {
    #global rpc_url
    awk -v rpc="$rpc_url&type=info" '{
        if (NR == 1)
            printf "%s&arg[]=%s", rpc, $0
        else if (NR % 150 == 0)
            printf "\n%s&arg[]=%s", rpc, $0
        else if (NR > 1)
            printf "&arg[]=%s", $0
    } END {
        printf "\n"
    }'
}

uri_search() {
    #global rpc_url
    awk -v rpc="$rpc_url&type=search&by=$1&arg" '{
        printf "%s=%s\n", rpc, $0
    }'
}

usage() {
    plain 'usage: %s [-t [info|search] ] [-b by]' "$argv0" >&2
    exit 1
}

source /usr/share/makepkg/util/message.sh
source /usr/share/makepkg/util/parseopts.sh

if [[ ( -t 1 && -t 2 && ! -o xtrace && $AUR_COLOR == auto ) || $AUR_COLOR == always ]] ; then
    colorize
fi

opt_short='b:t:'
opt_long=('by:' 'type:' 'aur-url:' 'rpc-ver:' 'rpc-url:')
opt_hidden=('dump-options')

if ! parseopts "$opt_short" "${opt_long[@]}" "${opt_hidden[@]}" -- "$@"; then
    usage
fi
set -- "${OPTRET[@]}"

unset by type
while true; do
    case "$1" in
        -b|--by)   shift; by=$1 ;;
        -t|--type) shift; type=$1 ;;
        --rpc-ver) shift; rpc_ver=$1 ;;
        --rpc-url) shift; rpc_url=$1 ;;
        --dump-options) printf -- '--%s\n' "${opt_long[@]}" ;
                        printf -- '%s' "${opt_short}" | sed 's/.:\?/-&\n/g' ;
                        exit ;;
        --) shift; break ;;
    esac
    shift
done

# set filters
case $type in
      info) uri() { uri_info; } ;;
    search) uri() { uri_search "${by:-name-desc}"; } ;;
         *) usage ;;
esac

# store output on error
wget_log=$(mktemp -t wget.XXXXXXXX)
trap 'rm -rf "$wget_log"' EXIT

# check for interactive terminal
if [[ -t 0 ]]; then
    cat >&2 <<EOF
Warning: Input is read from the terminal. You either know what you
Warning: are doing, or you forgot to pipe data into $argv0.
Warning: Press CTRL-D to exit.
EOF
fi

# pipeline
jq -R -r '@uri' | uri | wget -o "$wget_log" -i - -O - -nv
wget_err=${PIPESTATUS[2]}

if ((wget_err)); then
    cat "$wget_log" >&2
    exit "$wget_err"
fi

# vim: set et sw=4 sts=4 ft=sh:
