#!/bin/bash
# aur-build-nspawn - build packages using systemd-nspawn
set -o errexit
readonly argv0=build-nspawn
readonly PATH=/bin:/usr/bin
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

machine=$(uname -m)
directory=/var/lib/aurbuild/$machine
makechrootpkg_args=(-cu)
makepkg_conf=/usr/share/devtools/makepkg-$machine.conf
pacman_conf=/usr/share/devtools/pacman-extra.conf
mode=build

conf_devtools() {
    printf '[options]\n'
    pacconf --config="$1" --options --raw

    # https://git.archlinux.org/devtools.git/tree/mkarchroot.in#n54
    printf '#CacheDir=\n'
}

conf_repo() {
    while IFS= read -r; do
        printf '[%s]\n' "$REPLY"
        pacconf --repo="$REPLY" --raw
    done
}

trap_exit() {
    if ! [[ -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

usage() {
    printf >&2 -- 'usage: %s [-CDMu] [-d db] -- <args>' "$argv0" >&2
    exit 1
}

unset database
while getopts :C:D:M:d:u opt; do
    case $opt in
        C) pacman_conf=$OPTARG  ;;
        D) directory=$OPTARG    ;;
        M) makepkg_conf=$OPTARG ;;
        d) database=$OPTARG     ;;
        u) mode=update          ;;
        *) usage                ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if (($#)); then
    makechrootpkg_args=("$@")
fi

readonly pacman_conf makepkg_conf directory database prepare

trap 'trap_exit' EXIT
tmp=$(mktemp -d)

# XXX Duplication between "update" mode and makechrootpkg -u
case $mode in
    update)
        { conf_devtools "$pacman_conf"
          pacconf --repo-list | conf_repo
        } >"$tmp"/pacman.conf

        if [[ -f $directory/root/.arch-chroot ]]; then
            # locking is done by systemd-nspawn
            arch-nspawn -C "$tmp"/pacman.conf -M "$makepkg_conf" \
                        "$directory"/root pacman -Syu --noconfirm
        else
            install -d "$directory" -m 755 -v || exit
            mkarchroot  -C "$tmp"/pacman.conf -M "$makepkg_conf" \
                        "$directory"/root base-devel
        fi

        if [[ -v database ]]; then
            pacconf --sysroot="$directory"/root --repo="$database" >/dev/null
        fi
	    ;;
    build)
        PKGDEST="${PKGDEST:-$PWD}" makechrootpkg \
               -r "$directory" "${makechrootpkg_args[@]}"
        ;;
esac

# vim: set et sw=4 sts=4 ft=sh:
