#!/bin/bash
# shellcheck disable=SC2086
# build--sync - helper for upgrading local repository
set -o errexit
[[ -v AUR_DEBUG ]] && set -o xtrace
AUR_PACMAN_AUTH=${AUR_PACMAN_AUTH:-sudo}
argv0=build--sync
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

if (( ! $# )); then
    printf >&2 '%s: repository not specified\n' "$argv0"
    exit 1
fi

# propagate local repo contents
arg_repo=$1
$AUR_PACMAN_AUTH pacsync "$arg_repo"
$AUR_PACMAN_AUTH pacsync "$arg_repo" --dbext=.files

# retrieve upgrade targets
targets=()
while IFS='/' read -r repo name; do
    if [[ $repo == "$arg_repo" ]]; then
        targets+=("$repo/$name")
    fi
done < <(pacman -Sup --print-format '%r/%n')
wait "$!"

if (( ${#targets[@]} )); then
    printf >&2 "%s: upgrading packages in repository '%s'\n" "$argv0" "$arg_repo"
    printf '%s\n' "${targets[@]}" | $AUR_PACMAN_AUTH pacman -S --noconfirm -
fi

# vim: set et sw=4 sts=4 ft=sh:
