#!/bin/bash
# aur-fetch-snapshot - retrieve build files using tar archives
set -o errexit
shopt -s nullglob
readonly argv0=fetch-snapshot
readonly startdir=$PWD
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

dl_stdin() {
    if type -P aria2c >/dev/null; then
        aria2c --no-conf=true --stderr=true -i -
    else
        wget -i -
    fi
}

tar_no_mode_diff() {
    if [[ -d $2/${1%%.tar*} ]]; then
        LC_MESSAGES=C tar -df "$1" -C "$2" | grep -Evq '(Mode|Uid|Gid)'
    else
        return 1
    fi
}

usage() {
    printf -- >&2 'usage: %s [-L log_dir]\n' "$argv0"
    exit 1
}

not_a_directory() {
    printf -- >&2 '%s: %q: not a directory\n' "$argv0" "$1"
    exit 20
}

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

log_dir=/dev/stdout
while getopts :L: opt; do
    case $opt in
        L) log_dir=$OPTARG ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if [[ $log_dir == /dev/stdout ]]; then
    merge_log() { tee; }
elif [[ -d $log_dir ]]; then
    merge_log() { tee -a "$log_dir/$1".diff | diffstat -CKq -f3; }
else
    not_a_directory "$log_dir"
fi

tmp=$(mktemp -dt "$argv0".XXXXXXXX)
trap trap_exit EXIT

cd "$tmp"
dl_stdin

for a in ./*.tar.gz; do
    tar -kxf "$a"

    if tar_no_mode_diff "$a" "$startdir"; then
        a=${a%%.tar.gz}

        diff -ur "$startdir/$a" "$a" | merge_log "$a"
    fi
    cp -af "${a%%.tar.gz}" "$startdir"
done

# vim: set et sw=4 sts=4 ft=sh:
