#!/bin/bash
readonly argv0=deps
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
declare mode=rpc

find_srcinfo() {
    find "$@" -maxdepth 1 -type f -name .SRCINFO -print0
}
readonly -f find_srcinfo

usage() {
    printf -- 'usage: %s [-sr] package [package...]\n' "$argv0" >&2
    exit 1
}
readonly -f usage

while getopts :jp opt; do
    case $opt in
        p) mode=src ;;
        j) mode=rpc ;;
        *) usage    ;;
    esac
done
shift $((OPTIND -1))
OPTIND=1

case $mode in
    src)
        mapfile -t arg_path < <(readlink -e -- "$@")

        if [[ -z ${arg_path[*]} ]]; then
            printf -- '%s: no data available\n' "$argv0"
        fi

        find_srcinfo "${arg_path[@]}" | aur deps-src | grep -Fxf <(basename -a "$@")
        ;;
    rpc)
        printf -- '%s\n' "$@" | aur deps-rpc
        ;;
esac


