#!/bin/bash
# build--sync - helper for upgrading local repository
set -e
[[ -v AUR_DEBUG ]] && set -o xtrace
argv0=build--sync
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

if (( ! $# )); then
    printf >&2 'error: repository not specified\n'
    exit 1
fi

arg_repo=$1
pacsync "$arg_repo"
pacsync "$arg_repo" --dbext=.files

targets=()
while IFS='/' read -r repo name; do
    if [[ $repo == "$arg_repo" ]]; then
        targets+=("$name")
    fi
done < <(
    pacman -Sup --print-format '%r/%n'
)
wait $!

if (( ${#targets[@]} )); then
    printf >&2 "%s: upgrading packages in repository '%s'\n" "$argv0" "$arg_repo"
    pacman -S --noconfirm "${targets[@]}"
fi

# vim: set et sw=4 sts=4 ft=sh:
