#!/bin/bash
# shellcheck disable=SC2016
# aur-srcver - update and print package revisions
readonly argv0=srcver
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
readonly startdir=$PWD

get_pkgbuild_info() {
    env -C "$1" -i bash -c '
        PATH= source PKGBUILD

        if [[ -v epoch ]]; then
            fullver=$epoch:$pkgver-$pkgrel
        else
            fullver=$pkgver-$pkgrel
        fi

        printf %s\\t%s\\n "${pkgbase:-$pkgname}" "$fullver"
    '
}

find_pkgbuild_path() {
    find "$@" -maxdepth 1 -type f -name PKGBUILD -printf '%h\n'
}

usage() {
    printf 'usage: %s path [path...]\n' "$argv0" >&2
    exit 1
}

trap_exit() {
    if ! [[ -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

if ((!$#)); then
    usage
fi

# XXX trickery for hyphen and absolute path arguments
mapfile -t arg_path < <(readlink -e -- "$@")

tmp=$(mktemp -dt "$argv0".XXXXXXXX) || exit
trap 'trap_exit' EXIT

cd "$tmp" || exit
parallel --will-cite --nice 10 -j +2 --joblog makepkg_log --results '{#}_makepkg' \
  'cd {}; makepkg --skipinteg --noprepare -od' &>/dev/null ::: "${arg_path[@]}"
num_failed=$?

if [[ "$num_failed" -gt 0 ]]; then
    printf >&2 '%s: failed to update %s packages\n\n' "$argv0" "$num_failed"

    while IFS=$'\t' read -r seq _ _ _ _ _ exitcode _ command; do
        [[ "$exitcode" -eq 0 ]] && continue

        printf >&2 '8<----\n'
        printf >&2 '%s\n' "$command"
        cat "${seq}_makepkg" >&2
        cat "${seq}_makepkg.err" >&2
        printf >&2 '8<----\n\n'
    done <makepkg_log
fi

find_pkgbuild_path "${arg_path[@]}" | while read -r; do
    get_pkgbuild_info "$REPLY"
done

# vim: set et sw=4 sts=4 ft=sh:
