#!/bin/bash
readonly argv0=rpc-deps
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o noclobber

declare mode=aur

count() {
    declare -i num

    if num=$(jq -r '.resultcount' "$1" | awk '{s += $1} END {print s}'); then
        printf '%d' "$num"
    else
        printf '%s: invalid argument\n' "$argv0" >&2
        exit 22
    fi
}
readonly -f count

sort_by() {
    awk 'FNR == NR {
        a[$1] = $0; next
    } {
        if($0 in a)
            print a[$0]
    }' "$@"
}
readonly -f sort_by

tr_ver() {
    sed -r 's/[<>=].*$//g'
}
readonly -f tr_ver

tabulate() {
    jq -r '.results[]
        | .Name         as $name
        | .PackageBase  as $base
        | .Version      as $ver
        | .URLPath      as $url
        | ([$name] + .Depends + .MakeDepends + .CheckDepends)[]?
        | [$name, ., $base, $ver, $url] | @tsv' "$1"
}
readonly -f tabulate

chain() {
    declare -i num

    # XXX move argv to aur(1)
    printf -- '%s\n' "$@" | aur rpc -t info > json/0 || exit
    num=$(count json/0)

    if [[ $num -lt 1 ]]; then
        printf '%s: no packages found\n' "$argv0" >&2
        exit 1
    fi

    for ((a = 1; a <= 30; ++a)); do
        declare -i sub=$((a-1))

        tabulate json/$sub | tee -a tsv/n > tsv/$sub

        cut -f1 tsv/$sub >> pkgname
        cut -f1 tsv/$sub >> seen

        # Avoid querying duplicates (#4)
        cut -f2 tsv/$sub | tr_ver | grep -Fxvf seen | aur rpc -t info > json/$a || exit

        if [[ -s json/$a ]]; then
            num=$(count json/$a)
        else
            break
        fi

        if ((num >= 1)); then
            cut -f2 tsv/$sub >> seen
        else
            break
        fi
    done

    if ((a > 30)); then
        printf '%s: total requests: %d (out of range)\n' "$argv0" $((++a)) >&2
        exit 34
    fi

    if ! cut -f1,2 tsv/n | tr_ver | tsort; then
        printf '%s: invalid argument\n' "$argv0" >&2
        exit 22
    fi
 
    cut -f2 --complement tsv/n | sort -uk1,1 > pkginfo
}
readonly -f chain

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}
readonly -f trap_exit

usage() {
    printf 'usage: %s [-at] pkgname...\n' "$argv0" >&2
    exit 1
}
readonly -f usage

while getopts :at OPT; do
    case $OPT in
        a) mode=all ;;
        t) mode=tab ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ((!$#)); then
    usage
fi

tmp=$(mktemp -dt "$argv0".XXXXXXXX) || exit
trap 'trap_exit' EXIT

if cd "$tmp" && mkdir json tsv; then
    chain "$@" > order
else
    exit
fi

case $mode in
    aur) grep -Fxf pkgname order | tac ;;
    all) tac order ;;
    tab) tac order | sort_by pkginfo - ;;
esac

# vim: set et sw=4 sts=4 ft=sh:
