#!/bin/bash
readonly argv0=deps-src
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o pipefail

deps_paired() {
    awk -v FS='[<=>]' '
    /pkgbase/ {
        read = 1; pb = $2

        printf("%s %s\n", pb, pb)
    } {
        if (read && $0 ~ /^\t(make|check)?depends/)
            printf("%s %s\n", pb, $2)

        if ($0 ~ /^$/)
            read = 0 # split package
    }' "$@"
}
readonly -f deps_paired

# XXX Output of form " pkgname pkgbase" (leading space)
base() {
    awk -v FS='[<=>]' '
    /pkgbase/ {
        pb = $2
    }
    /pkgname/ {
        printf("%s %s\n", $2, pb)
    }' "$@"
}
readonly -f base

sub() {
    awk 'NR == FNR {
        x[$1] = $2; next
    } {
        if ($1 in x && !(x[$1] in seen)) {
            print x[$1]; seen[x[$1]];
        }
    }' "$@"
}
readonly -f sub

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}
readonly -f trap_exit

tmp=$(mktemp -t "$argv0".XXXXXXXX) || exit
trap 'trap_exit' EXIT

xargs -0 cat >"$tmp"

if [[ -s "$tmp" ]]; then
    deps_paired "$tmp" | tsort | sub <(base "$tmp") -
fi

# vim: set et sw=4 sts=4 ft=sh:
