#!/bin/bash
readonly argv0=deps-src
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
set -o pipefail

deps_paired() {
    awk -v FS='[<=>]' '
    /pkgbase/ {
        read = 1; pb = $2

        printf("%s\t%s\n", pb, pb)
    } {
        if (read && $0 ~ /^\t(make|check)?depends/)
            printf("%s\t%s\n", pb, $2)

        if ($0 ~ /^$/)
            read = 0    # split package
    }' "$@"
}
readonly -f deps_paired

# XXX Output of form " pkgname\tpkgbase" (leading space)
base() {
    awk -v FS='[<=>]' '
    /pkgbase/ {
        pb = $2
    }
    /pkgname/ {
        printf("%s\t%s\n", $2, pb)
    }' "$@"
}
readonly -f base

sub() {
    awk 'NR == FNR {
        x[$1] = $2; next
    } {
        if ($1 in x && !(x[$1] in seen)) {
            print x[$1]; seen[x[$1]];
        }
    }' "$@"
}
readonly -f sub

trap_exit() {
    if [[ ! -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}
readonly -f trap_exit

usage() {
    printf 'usage: %s path [path...]\n' "$argv0" >&2
    exit 1
}
readonly -f usage

while getopts h opt; do
    case $opt in
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ((!$#)); then
    usage
fi

tmp=$(mktemp -t "$argv0".XXXXXXXX) || exit
trap 'trap_exit' EXIT

# XXX take file names from stdin (null-separated?) -> aur-deps wrapper
mapfile -t arg_path < <(readlink -e -- "$@")

if [[ -n ${arg_path[*]} ]]; then
    find "${arg_path[@]}" -maxdepth 1 -type f -name .SRCINFO -print0 \
        | xargs -0 cat > "$tmp"
fi

if [[ -s "$tmp" ]]; then
    deps_paired "$tmp" | tsort | sub <(base "$tmp") - \
        | grep -Fxf <(printf -- '%s\n' "${@##*/}") | tac
fi

# vim: set et sw=4 sts=4 ft=sh:
