#!/bin/bash
# aur-srcver - update and print package revisions
readonly argv0=srcver
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
readonly startdir=$PWD

srcver_pkgbuild_info() {
    env -C "$1" -i bash -c '
        PATH= source PKGBUILD

        if [[ -v epoch ]]; then
            fullver=$epoch:$pkgver-$pkgrel
        else
            fullver=$pkgver-$pkgrel
        fi

        printf %s\\t%s\\n "${pkgbase:-$pkgname}" "$fullver"
    '
}
export -f srcver_pkgbuild_info

srcver_pkgbuild_path() {
    if env -C "$1" makepkg --skipinteg -od; then
        srcver_pkgbuild_info "$1" >> "$2"
    else
        return
    fi
}
export -f srcver_pkgbuild_path

trap_exit() {
    if ! [[ -o xtrace ]]; then
        rm -rf "$tmp"
    fi
}

if ! (($#)); then
    printf >&2 'usage: %s path...\n' "$argv0"
    exit 1
fi

tmp=$(mktemp -dt "$argv0".XXXXXXXX) || exit
trap 'trap_exit' EXIT

aur jobs --nice 10 -j +2 --joblog "$tmp"/makepkg_log --results "$tmp/{#}_makepkg" \
    srcver_pkgbuild_path '{}' "$tmp"/results ::: "$@" >/dev/null 2>&1
jobs_exit=$?

if ((jobs_exit > 101)); then
    printf >&2 '%s: error running "parallel", exit code %d\n' "$argv0" "$jobs_exit"
    exit "$jobs_exit"
fi

if ((jobs_exit > 0)); then
    printf >&2 '%s: failed to update %s packages\n' "$argv0" "$jobs_exit"

    while IFS=$'\t' read -r seq _ _ _ _ _ makepkg_exit _ command; do
        if ((makepkg_exit)); then
            printf >&2 '8<----\n'
            printf >&2 '%s\n' "$command"

            cat "$tmp/${seq}_makepkg" >&2
            cat "$tmp/${seq}_makepkg.err" >&2
        else
            continue
        fi
    done < "$tmp"/makepkg_log

    exit "$jobs_exit"
else
    cat "$tmp"/results
fi

# vim: set et sw=4 sts=4 ft=sh:
