#!/bin/bash
readonly argv0=checkupdates
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

namever_sync() {
    xargs -0r pacman -Sddp --print-format "$(printf '%%n\t%%v')"
}
readonly -f namever_sync

parse_sync() {
    pacsift --exact --repo="$1" --null <&- | namever_sync
}
readonly -f parse_sync

# XXX parse_local()
#     parse_sync_any()

while getopts :d: OPT; do
    case $OPT in
        d) parse_sync "$OPTARG" | aur vercmp ;;
    esac
done
