#!/bin/bash
# aur-deps - order package dependencies
readonly argv0=deps
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
mode=json

find_srcinfo() {
    find "$@" -maxdepth 1 -type f -name .SRCINFO -print0
}

usage() {
    printf -- 'usage: %s [-sr] package [package...]\n' "$argv0" >&2
    exit 1
}

while getopts :jp opt; do
    case $opt in
        p) mode=src  ;;
        j) mode=json ;;
        *) usage     ;;
    esac
done
shift $((OPTIND -1))
OPTIND=1

if ((!$#)); then
    usage
fi

case $mode in
    src)
        mapfile -t arg_path < <(readlink -e -- "$@")

        if [[ -z ${arg_path[*]} ]]; then
            printf -- '%s: no data available\n' "$argv0"
        fi

        find_srcinfo "${arg_path[@]}" | aur deps-src | grep -Fxf <(basename -a "$@")
        ;;
    json)
        printf -- '%s\n' "$@" | aur deps-rpc
        ;;
esac
