#!/bin/bash
readonly argv0=rfilter
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
readonly arch_repo=(core extra testing community{,-testing} multilib{,-testing})

declare -A pkgset

provides() {
    expac '%n %R %S' -Sv -- "$@" | awk '{
        for(i = 2; i <= NF; ++i) {
            printf("%s\t%s\n", $1, $i) | "sort -u"
        }
    }'
}

usage() {
    printf 'usage: %s [-d repo]\n' "$argv0" >&2
    exit 1
}

readonly -f provides usage

unset repo siftargs user_repo
while getopts d: OPT; do
    case $OPT in
        d) user_repo+=("$OPTARG") ;;
        *) usage ;;
    esac
done
shift $((OPTIND - 1))
OPTIND=1

if ! [[ -v user_repo ]]; then
    user_repo=("${arch_repo[@]}")
fi

mapfile -t all < /dev/stdin

for p in "${all[@]}"; do
    siftargs+=("--satisfies=$p")
    pkgset[$p]=1
done

if [[ ${pkgset[*]} ]]; then
    for p in "${user_repo[@]}"; do
        siftargs+=("--repo=$p")
    done
else
    printf '%s: no data available\n' "$argv0" >&2
    exit 61
fi

# https://github.com/andrewgregory/pacutils/issues/3
mapfile -t query < <(pacsift --sync --exact "${siftargs[@]}" <&-)

if [[ ${query[*]} ]]; then
    while read -r p v; do
        p=${p#*/}

        if [[ ${pkgset[$p]} ]]; then
            repo+=("$p")
        fi

        if [[ ${pkgset[$v]} ]]; then
            printf 'virtual dependency %s provided by %s\n' "$v" "$p" >&2
            repo+=("$v")
        fi
    done < <(provides "${query[@]}")
fi

grep -Fxvf <(printf '%s\n' "${repo[@]}") <(printf '%s\n' "${all[@]}")

# vim: set et sw=4 sts=4 ft=sh:
