#!/bin/bash
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
argv0=build-asroot
startdir=$PWD
PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

# default options
makepkg_args=(-L) pactrans_args=(--no-confirm) repo_add_args=(-R) checkdepends=1

# Allow to drop permissions for commands as needed (#907)
as_user() {
    local USER HOME SHELL

    if [[ $UID == 0 ]] && [[ -v build_user ]]; then
        # runuser --pty messes up the terminal with AUR_DEBUG set, use setpriv(1)
        # and replicate the runuser(1) behavior for setting the environment
        { IFS= read -r USER
          IFS= read -r HOME
          IFS= read -r SHELL
        } < <(getent passwd "$build_user" | awk -F: '{printf("%s\n%s\n%s\n", $1, $6, $7); }')

        setpriv --reuid "$build_user" --regid "$build_user" --init-groups \
                env USER="$USER" HOME="$HOME" LOGNAME="$USER" SHELL="$SHELL" "$@"
    else
        env "$@"
    fi
}

# Save transaction so that it can easily be undone later
get_transaction() {
    if (( ! $# )); then
        env LANG=C pacinstall "${pactrans_args[@]}" --print-only "$@" |
            awk '$0 ~ /^removing/ || $0 ~ /^installing/ { print }'
        return "${PIPESTATUS[0]}"
    fi
}

install_depends() {
    #global remove_args install_args
    if (( ${#remove_args[@]} + ${#install_args[@]} )); then
        pacinstall "${pactrans_args[@]}" --as-deps "${install_args[@]}" --remove "${remove_args[@]}"
    fi
}

remove_depends() {
    #global remove_args install_args
    if (( ${#remove_args[@]} + ${#install_args[@]} )); then
        pacremove "${pactrans_args[@]}" "${install_args[@]##*/}" --install "${remove_args[@]}"
    fi
}

# Simple option parsing
unset queue build_user db_name

orig_argv=("$@")
while getopts :a:U:d:f OPT; do
    case $OPT in
        a) queue=$OPTARG ;;
        d) db_name=$OPTARG ;;
        U) build_user=$OPTARG ;;
        f) makepkg_args+=(-f) ;;
        *) printf >&2 '%s: invalid option\n' "$argv0"
           exit 1;;
    esac
done
shift $(( OPTIND - 1 ))

if (( $(id -u "$build_user") == 0 )); then
    printf '%s: build user is privileged\n' "$argv0"
    exit 2
fi

# elevate permissions
if (( EUID != 0 )); then
    exec ${AUR_PACMAN_AUTH:-sudo} -- "${BASH_SOURCE[0]}" "${orig_argv[@]}"
fi

db_path=$(as_user aur repo -d "$db_name" --path)
db_root=$(dirname "$db_path")

# set kinds of dependencies that will be installed before the build
deptypes=(depends makedepends)
(( checkdepends )) && deptypes+=(checkdepends)

if [[ -v queue ]]; then
    exec {fd}< "$queue"
else
    exec {fd}< <(printf '\n')
fi

# process queue
unset remove_args install_args
trap 'remove_depends' EXIT

while IFS= read -ru "$fd" path; do
    cd "$startdir"
    cd "$path"

    # retrieve dependencies as build user
    depends=()
    while IFS= read -r value; do
        depends+=("$value")
    done < <(
        as_user aur build--pkglist --srcinfo | pacini - "${deptypes[@]}" | awk -F' = ' '{print $2}')

    # check which dependencies are missing on the host
    mapfile -t depends_missing < <(pacman -T "${depends[@]}")

    # precompute the transaction and install dependencies
    while read -r type package _; do
        case $type in
            removing)
                remove_args+=("${package##local/}") ;;
            installing)
                install_args+=("$package") ;;
        esac
    done < <(get_transaction "${depends_missing[@]}")
    wait "$!"

    install_depends

    # build the package
    makepkg_ret=0
    as_user PKGDEST="$db_root" makepkg "${makepkg_args[@]}" || makepkg_ret=$?

    if (( makepkg_ret == 13 )); then
        continue  # $E_ALREADY_BUILT
    elif (( makepkg_ret > 0 )); then
        exit "$ret"
    fi

    # perform dependency transaction in reverse order
    # Note: the install reason for removed packages is not preserved.
    remove_depends
    unset install_args remove_deps

    # retrieve paths to built packages
    mapfile -t pkglist < <(as_user PKGDEST="$db_root" aur build--pkglist)
    wait "$!"

    # update local repository
    as_user env -C "$db_root" repo-add "${repo_add_args[@]}" "$db_path" "${pkglist[@]}"

    # update host and pacman database
    aur build--sync "$db_name"
done

exec {fd}<&-
