#!/bin/bash
[[ -v AUR_DEBUG ]] && set -o xtrace
set -o errexit
shopt -s extglob

# Helper function to take complements of pkgbase arrays
filter_packages() { grep -Fxvf <(printf '%s\n' "$@") -; }

# Directory with diffs and PKGBUILD subdirs
cd "${1:-/dev/null}"
diffs=(@(*.diff|*.log))
pkgbases=(*/)
pkgbases=("${pkgbases[@]%/}")

# Show diffs in 2 panes
if [[ -f ${diffs[0]} ]]; then
    cat "${diffs[@]}" | diff-so-fancy | less --tabs=4 -RX

    # Remove diffs from remaining targets (new or unchanged dirs)
    mapfile -t pkgbases < <(
        printf '%s\n' "${pkgbases[@]}" | filter_packages "${diffs[@]%%.*}")
fi

# Show remaining targets in a concatenated fashion
if (( ${#pkgbases[@]} )); then
    find -L "${pkgbases[@]}" -maxdepth 1 -type f -exec bat {} +
fi

# Show an exit prompt
read -rp $'Press Return to continue or Ctrl+d to abort\n'
