'\" t
.TH AURHOSTING 7 2018-02-05 AURUTILS
.SH NAME
aurhosting \- host pacman repositories using git

.SH ADVANTAGES
.SS Atomic changesets

Each revision can be viewed as a single set of packages. This provides
a way for every commit to be an atomic operation allowing for mirrors
to synchronise consistently. Each mirror can then make a shallow
clone of the repository while still only recovering changed packages
reducing bandwidth while maintaining atomicity without additional
scripting or tooling.

.SS Changeset based roll back

Rolling back using changesets is usually done by specifying the commit
checksum in the Server directive and allows for rolling back based on
changesets rather than needing to manage finely grained version
dependencies.

.SH DISADVANTAGES
.SS Requires raw file access

The server hosting the git repository needs a mechanism to expose raw
files directly using a simple and consistent layout so that files can
be downloaded using dead reckoning.

.SH HOSTING TEMPLATES

.EX
https://cgit/$repo.git/plain/
https://gitlab.com/$user/$repo/raw/${commit:-master}/
https://try.gogs.io/$user/$repo/raw/${commit:-master}/
http://repo.or.cz/$repo.git/blob_plain/${commit:-HEAD}:/
https://raw.githubusercontent.com/$user/$repo/${commit:-master}/
.EE

.SH EXAMPLES 
.SS Using github.com
.EX
% vi pacman.conf

  [earnestly]
  SigLevel = PackageOptional
  Server = https://raw.githubusercontent.com/Earnestly/earnestly/master

% repose -fvzr ~/earnestly earnestly
adding stlink-git 1.3.1.r17.g5c10d4b-1
writing earnestly.db...
writing earnestly.files...

% sudo pacman -Syu
:: Synchronising package databases...
earnestly        32.7 KiB  0.00B/s 00:00 [----------------------------] 100%

% pacman -Sl earnestly
earnestly stlink-git 1.3.1.r17.g5c10d4b-1

% sudo pacman -S stlink-git
resolving dependencies...
looking for conflicting packages...

Package (1)           New Version           Net Change  Download Size

earnestly/stlink-git  1.3.1.r17.g5c10d4b-1    0.41 MiB       0.09 MiB

Total Download Size:   0.09 MiB
Total Installed Size:  0.41 MiB

:: Proceed with installation? [Y/n]
.EE

.SH AUTHORS
.MT https://github.com/Earnestly
Earnestly
.ME
