#!/bin/bash

have_optdump=('build' 'depends' 'fetch' 'pkglist' 'repo' 'repo-filter' 'query'
              'search' 'srcver' 'sync' 'vercmp')
no_optdump=('graph')

corecommands=()

for cmd in "${have_optdump[@]}"; do
    mapfile -t opts < <(bash "../lib/aur-${cmd}" --dump-options | LC_ALL=C sort)
    corecommands+=("    default_cmds[${cmd}]='${opts[*]}'")
done

for cmd in "${no_optdump[@]}"; do
    corecommands+=("    default_cmds[${cmd}]=''")
done

while IFS= read -r line; do
    case "${line}" in
        *DEFAULT_OPTS)
            printf '%s\n\n' "${line%DEFAULT_OPTS}typeset -A default_cmds"
            printf '%s\n' "${corecommands[@]}"
            ;;
        *)
            printf '%s\n' "${line}" ;;
    esac
done < "$1"
