#!/bin/bash
set -e

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar

# issue 216: aur-sync with unset variables
env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u XDG_CACHE_HOME -u AURDEST -u AUR_SYNC_NINJA AUR_ENV=/dev/null \
    aur sync -d "$tmp_uid" aurutils --pacman-conf "$tmp"/pacman.conf -o --no-view --no-ver
