#!/bin/bash
set -e

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar
pkg=weston-git
pkg_ignored=wayland-git

# check ignores from shell substitution
env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u XDG_CACHE_HOME -u AUR_SYNC_NINJA AUR_ENV=/dev/null AURDEST="$tmp" \
    aur sync -d "$tmp_uid" --no-build --no-view --pacman-conf "$tmp"/pacman.conf --ignore-file <(echo "$pkg_ignored") "$pkg"

[[ ! -d $tmp/$pkg_ignored ]]
[[ ! -f $tmp/$pkg_ignored ]]
