#!/bin/bash
# exit early on dependency cycles
# regression in commit 01af4500d77ac1bce6105089603051b4ad554c92 (#908)
cycles_target=ruby-activemodel

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar

env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT AUR_ENV=/dev/null AUR_SYNC_USE_NINJA=0 AURDEST="$tmp" \
    aur sync --no-view --no-build --pacman-conf "$tmp"/pacman.conf "$cycles_target"
(( $? == 22 ))

env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT AUR_ENV=/dev/null AUR_SYNC_USE_NINJA=1 AURDEST="$tmp" \
    aur sync --no-view --no-build --pacman-conf "$tmp"/pacman.conf "$cycles_target"
(( $? == 22 ))
