#!/bin/bash
set -o pipefail
tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT

paste_args() {
    printf '%s\n' "${@:2}" | jq -R -r '@uri' | paste -s -d "$1"
}

# randomized test
n_terms=10
set -- $(aur pkglist | shuf -n "$n_terms")
printf '%s\n' >&2 "$*"
cd "$tmp"

# RPC query (set intersection)
aur search --format '%n\n' "$@" | sort >"$tmp"/a

# Website query
curl -s "https://aur.archlinux.org/packages?K=$(paste_args '+' "$@")" | \
    hq 'tbody > tr > td:first-child > a' text | sort >"$tmp"/b

# Identity required
[[ -z $(grep -Fvxf "$tmp"/a "$tmp"/b) ]] # B included in A
[[ -z $(grep -Fvxf "$tmp"/b "$tmp"/a) ]] # A included in B
