#!/bin/bash
set -o pipefail
export AUR_QUERY_RPC_POST=0
export AUR_QUERY_RPC_SPLITNO=1
export AUR_QUERY_PARALLEL=1

# search requests
for i in {1..10}; do
    printf 'search: %d/10\n' "$i"
    aur query --raw -t search 'perl' 'rpm' | jq >/dev/null
    (( $? != 0 )) && exit # results concatenated from both queries
done

# info requests
for i in {1..10}; do
    printf 'info: %d/10\n' "$i"
    aur query --raw -t info 'perl-git' 'rpm' | jq >/dev/null
    (( $? != 1 )) && exit # no results on second argument
done
