#!/bin/bash
set -e

tmp1=$(mktemp -d)
tmp1_uid=custom-$RANDOM-1
tmp2=$(mktemp -d)
tmp2_uid=custom-$RANDOM-2
tmp3=$(mktemp -d)
tmp3_uid=custom-$RANDOM-3
#trap 'rm -rf -- "$tmp1" "$tmp2" "$tmp3"' EXIT

cat >"$tmp1"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[$tmp1_uid]
SigLevel = Optional TrustAll
Server = file://$tmp1
[$tmp2_uid]
SigLevel = Optional TrustAll
Server = file://$tmp2
[$tmp3_uid]
SigLevel = Optional TrustAll
Server = file://$tmp3
EOF

# create local repository
repo-add "$tmp1/$tmp1_uid".db.tar
repo-add "$tmp2/$tmp2_uid".db.tar
repo-add "$tmp3/$tmp3_uid".db.tar

# issue 378: repository selection with AUR_REPO
env - AUR_REPO="$tmp1_uid" aur repo --path --config "$tmp1"/pacman.conf
env - AUR_REPO="$tmp2_uid" aur repo --path --config "$tmp1"/pacman.conf
env - AUR_REPO="$tmp3_uid" aur repo --path --config "$tmp1"/pacman.conf

