#!/bin/bash
set -e

tmp=$(mktemp -d)
#trap 'rm -rf -- "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

cat >"$tmp"/PKGBUILD <<EOF
pkgname=foo
pkgver=1
pkgrel=1
arch=('any')

package() {
    true
}
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar

# issue 513: PKGDEST (environment) should be ignored
env -C "$tmp" -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u MAKEPKG PKGDEST=/does/not/exist \
    aur build --no-sync -d "$tmp_uid" --pacman-conf "$tmp"/pacman.conf
tar -tf "$tmp"/foo-1-1-any.pkg.tar.zst

# vim: set et sw=4 sts=4 ft=sh:\n
