#!/bin/bash
set -e

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

cat >"$tmp"/PKGBUILD <<EOF
pkgname=foo
pkgver=1
pkgrel=1
arch=('any')

package() {
    true
}
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar

# issue 513: PKGDEST (environment) should be ignored
config=(--config "$tmp"/pacman.conf --pacman-conf "$tmp"/pacman.conf)
env -C "$tmp" PKGDEST=/does/not/exist aur build -d "$tmp_uid" "${config[@]}"

# vim: set et sw=4 sts=4 ft=sh:\n
