#!/bin/bash
set -e

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT
pkg1=aurutils
pkg2=aurutils-git

# expected: exit 0
env -C "$tmp" -u XDG_CONFIG_HOME -u AUR_LOCATION aur fetch "$pkg1" "$pkg2"

# expected: cloned repositories (x2)
ls "$tmp/$pkg1/.git"
ls "$tmp/$pkg2/.git"

# vim: set et sw=4 sts=4 ft=sh:\n
