#!/bin/bash
tmp=$(mktemp -d) || exit
trap 'rm -rf -- "$tmp"' EXIT

out=$(env -C "$tmp" - HOME=$HOME USER=$USER PATH=$PATH aur fetch aurutils aurutils-git)
err=$?

# expected: cloned repositories (x2), exit 0
(( err == 0 )) && [[ -d $tmp/aurutils/.git ]] && [[ -d $tmp/aurutils-git/.git ]]

# vim: set et sw=4 sts=4 ft=sh:\n
