#!/bin/bash
set -e

tmp=$(mktemp -d)
#trap 'rm -rf -- "$tmp"' EXIT
tmp_uid=custom-$RANDOM

cat >"$tmp"/pacman.conf <<EOF
[options]
HoldPkg = pacman-git glibc
Architecture = auto
CheckSpace
[core]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[community]
Include = /etc/pacman.d/mirrorlist
[$tmp_uid]
SigLevel = Optional TrustAll
Server = file://$tmp
EOF

# create local repository
repo-add "$tmp/$tmp_uid".db.tar

config=(--pacman-conf "$tmp"/pacman.conf)
pkg=aurutils
rev=5da2a05501a8f822bcea95ce4c39f1357bf730fe
ver=4

# checkout and build previous revision
cd "$tmp"
env - HOME=$HOME USER=$USER PATH=$PATH aur fetch "$pkg"

cd "$pkg"
git reset --hard "$rev"

env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u MAKEPKG aur build --no-sync \
     -rnd "$tmp_uid" --margs --skippgpcheck --pacman-conf "$tmp"/pacman.conf

fakeroot -- pacman --config "$tmp"/pacman.conf --dbpath "$tmp" -Sy
found_package=$(pacsift --config "$tmp"/pacman.conf --dbpath "$tmp" --repo="$tmp_uid" --satisfies="$pkg=$ver")
[[ -n $found_package ]]

# update to latest revision
cd -
env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u XDG_CACHE_HOME -u AUR_SYNC_NINJA AURDEST="$tmp" \
    aur sync --no-build --upgrades --ignore-file=/dev/null -d "$tmp_uid" --no-view --pacman-conf "$tmp"/pacman.conf

# build new version
cd "$pkg"
env -u AUR_REPO -u AUR_DBROOT -u AUR_DBEXT -u MAKEPKG aur build --no-sync \
    -rnd "$tmp_uid" --margs --skippgpcheck --pacman-conf "$tmp"/pacman.conf

fakeroot -- pacman --config "$tmp"/pacman.conf --dbpath "$tmp" -Sy
found_package=$(pacsift --config "$tmp"/pacman.conf --dbpath "$tmp" --repo="$tmp_uid" --satisfies="$pkg>$ver")
[[ -n $found_package ]]

# vim: set et sw=4 sts=4 ft=sh:\n
